### ISSUE TITLE
Parent/Upstream HTTP Proxy with Authentication

### ISSUE THREAD

**Issue by elog08** [snail007/goproxy#112]
I would like to use goproxy as a tunnel to an authenticated HTTP proxy.

goproxy:33080 -> user:pass@proxy.site:3333 -> www.example.org

I have tried the following:
`proxy http --always -t tcp -p ":33080" -T tcp -P "proxy.site:3333" -u "user" -A "pass"
`
`proxy http --always -t tcp -p ":33080" -T tcp -P "proxy.site:3333"  -A "user:pass"
`
but I get a Proxy Authorization error

```
curl -x localhost:33080 httpbin.org/ip
<html><head><title>407 Proxy Authentication Required</title></head>
<body><h2>407 Proxy Authentication Required</h2><h3>Access to requested resource disallowed by administrator or you need valid username/password to use this resource</h3></body></html>

```

Any help appreciated, 
Thanks

**Comment by snail007** [comment]
-A not supported by http(s) proxy , you can use sps model to do that, sps : https://github.com/snail007/goproxy#6proxy-protocol-conversion
