### ISSUE TITLE
how to compile it from src in ubuntutu 16.04-x64 ?

### ISSUE THREAD

**Issue by minotanoutman** [snail007/goproxy#116]
how to compile it from src in ubuntutu 16.04-x64 ?

**Comment by minotanoutman** [comment]
:~/goproxy/goproxy$ go build .
config.go:15:2: cannot find package "github.com/snail007/goproxy/sdk/android-ios" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/sdk/android-ios (from $GOROOT)
	($GOPATH not set)
config.go:16:2: cannot find package "github.com/snail007/goproxy/services" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services (from $GOROOT)
	($GOPATH not set)
config.go:19:2: cannot find package "github.com/snail007/goproxy/services/http" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/http (from $GOROOT)
	($GOPATH not set)
config.go:17:2: cannot find package "github.com/snail007/goproxy/services/kcpcfg" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/kcpcfg (from $GOROOT)
	($GOPATH not set)
config.go:20:2: cannot find package "github.com/snail007/goproxy/services/keygen" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/keygen (from $GOROOT)
	($GOPATH not set)
config.go:21:2: cannot find package "github.com/snail007/goproxy/services/mux" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/mux (from $GOROOT)
	($GOPATH not set)
config.go:22:2: cannot find package "github.com/snail007/goproxy/services/socks" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/socks (from $GOROOT)
	($GOPATH not set)
config.go:23:2: cannot find package "github.com/snail007/goproxy/services/sps" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/sps (from $GOROOT)
	($GOPATH not set)
config.go:24:2: cannot find package "github.com/snail007/goproxy/services/tcp" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/tcp (from $GOROOT)
	($GOPATH not set)
config.go:25:2: cannot find package "github.com/snail007/goproxy/services/tunnel" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/tunnel (from $GOROOT)
	($GOPATH not set)
config.go:26:2: cannot find package "github.com/snail007/goproxy/services/udp" in any of:
	/usr/lib/go-1.6/src/github.com/snail007/goproxy/services/udp (from $GOROOT)
	($GOPATH not set)
config.go:28:2: cannot find package "github.com/xtaci/kcp-go" in any of:
	/usr/lib/go-1.6/src/github.com/xtaci/kcp-go (from $GOROOT)
	($GOPATH not set)
config.go:29:2: cannot find package "golang.org/x/crypto/pbkdf2" in any of:
	/usr/lib/go-1.6/src/golang.org/x/crypto/pbkdf2 (from $GOROOT)
	($GOPATH not set)
config.go:30:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
	/usr/lib/go-1.6/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
	($GOPATH not set)

**Comment by snail007** [comment]
see manual

**Comment by snail007** [comment]
go get ./...
