### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by hefanbo** [snail007/goproxy#117]
### GoProxy
- Version: 5.2
- Installed with `install_auto.sh`

### VPS
- Provider: [Vultr](https://www.vultr.com)
- OS: Ubuntu 18.04 x64
- IP: 22.22.22.22
- Command:
```
$ proxy socks -t tls -p ":8080" -C /etc/proxy/proxy.crt -K /etc/proxy/proxy.key
```

### Local Server
- OS: Ubuntu 16.04 x64
- IP: 192.168.1.10
- Command:
```
$ proxy sps -t tcp -p 192.168.1.10:1080 -S socks -T tls -P 22.22.22.22:8080 -C /etc/proxy/proxy.crt -K /etc/proxy/proxy.key
```

### Client Machine
- OS: Ubuntu 18.04 x64
- IP: 192.168.1.101
- Visit `www.google.com` with Firefox. Proxy: socks5 192.168.1.10:1080

## Problem
- Cannot open websites from Client Machine
- Local Server reports
> connect to tls parent 22.22.22.22:8080 fail, ERR:proxy: failed to write greeting to SOCKS5 proxy at <span>www</span>.google.com:80: read tcp 192.168.1.10:60120->22.22.22.22:8080: i/o timeout from 192.168.1.101:37352
- VPS reports
> new methods request fail,ERR: read tcp 22.22.22.22:8080->XX.XX.XX.XX:25434: i/o timeout
- If goproxy runs on a VPS from another provider, Client Machine can visit websites, but the speed is slow and goproxy still reports `i/o timeout` frequently.

## Question
What should I do to locate the problem? How do I know if it is a bug or there is some problem with the provider's network?

## Detailed Log
[goproxy.log](https://github.com/snail007/goproxy/files/2227900/goproxy.log)

**Comment by snail007** [comment]
Firefox configuration error，use chrome and proxy plugin

**Comment by hefanbo** [comment]
Firefox + Proxy SwitchyOmega.
I don't think that's the problem because it can visit Google with other SOCKS5 proxy.
Anyway, I'll try Chromium+Proxy SwitchyOmega tomorrow.

**Comment by snail007** [comment]
the  log showing tcp data interaction between cs was timeouted, maybe your network to vps is slowly,try to grow timeout by argument --timeout , but wrong client also can lead the same  problem, this below may be help you,https://github.com/snail007/goproxy/wiki/小白开心上网

**Comment by hefanbo** [comment]
Tried Chromium+Proxy SwitchyOmega. Same error.
I do believe my browser proxy setting is correct because I've been using it for years. Both Firefox and Chromium don't work, and [tsocks](http://tsocks.sourceforge.net/) doesn't work either. They all work well with other SOCK5 proxy or GoProxy on other VPS.

Already tried increasing timeout value yesterday. Not working.
Actually, my network to VPS is fast enough (it's the fastest VPS I've ever had).

I've tested TCP connections between my VPS and my Local Server with [netcat](http://netcat.sourceforge.net/). It seems everything is OK.

The tutorial you provided in your last post doesn't help. I'm not a beginner.
I just don't have enough time to read through all the codes, so I'm asking for advices to quickly locate the problem, e.g., minimal test code for connections. It is strange that GoProxy works on other VPS, while there seems no problem with the connection to this VPS.

**Comment by snail007** [comment]
I guess you network to vps  be monitored,tls packet maybe has been dropped ,you  can use type  kcp improve it , kcp use udp transfer the tcp data and encrypted it .

**Comment by hefanbo** [comment]
Tested, and you're right. With KCP, the Client Machine can visit Google now, although the Local Server still complains `get out conn fail,dial tcp: i/o timeout,retrying...` a lot.
I'll continue to test TLS with some tools to confirm that's the problem. Thanks!

**Comment by hefanbo** [comment]
Confirmed that the TLS connection is interrupted, and even a simple HTTPS site won't work. The VPS provider (Vultr) says that TLS connections are blocked by some ISP from my country. I'v tried several locations that Vultr offers, but with no luck.

To those who have the same problem:
1. Use KCP if you only want to run GoProxy on your VPS.
2. If you also want to host HTTPS sites, try another VPS provider.
