### ISSUE TITLE
请问如何实现多代理

### ISSUE THREAD

**Issue by kenpingliu** [snail007/goproxy#118]
想要实现多个代理同时工作，并且二级地址也是分开的，例如
HTTP 0.0.0.0:8081 的下一级是 22.22.22.21:38080
HTTP 0.0.0.0:8082 的下一级是 22.22.22.22:38080
HTTP 0.0.0.0:8083 的下一级是 22.22.22.23:38080
HTTP 0.0.0.0:8084 的下一级是 22.22.22.24:38080
这样相当于同时在本机有4个代理服务器在工作，但是每个代理服务器的二级都是不相同的。

**Comment by snail007** [comment]
启动多个即可,只要端口不冲突就行了。

**Comment by kenpingliu** [comment]
@snail007 谢谢！
