### ISSUE TITLE
老版本的 goproxy for heroku 服务用现在的客户端如果连接

### ISSUE THREAD

**Issue by DreamUFO** [snail007/goproxy#119]
有没有大佬 指点下 goproxy for heroku 用了好几年了
一直用的Python 客户端 现在想用新的客户端 特别是for Android的
不知道该怎么配 望大佬指点下
http -t tcp -p "0.0.0.0:8089" -T tcp -P "https://appname.herokuapp.com/index.go" -A "password"
这样配的 报如下错误:
connect to https://appname.herokuapp.com/index.go , err:dial tcp: lookup tcp///appname.herokuapp.com/index.go: getaddrinfow: The specified class was not found.

**Comment by snail007** [comment]
本项目并没有"goproxy for heroku",是不是同名项目搞错了.
