### ISSUE TITLE
内网穿透支持范围端口

### ISSUE THREAD

**Issue by 102010cncger** [snail007/goproxy#12]
感谢大神

因为一些特殊的需要,本地开启了5001~5200的端口,不知道是否支持范围端口转发,默认支持
-r ":5001@:5001" ~-r ":5200@:5200"
 这样的规则

谢谢了!

**Comment by snail007** [comment]
这个需求比较定制，建议用程序生成 -r ":5001@:5001"  -r ":5001@:5001"  .....  -r ":5200@:5200" 这样的参数来实现，不用手动一个个写。
