### ISSUE TITLE
【kcp-socks5】get out conn fail,read method reply fail,i/o timeout,retrying...

### ISSUE THREAD

**Issue by joostshao** [snail007/goproxy#123]
./proxy socks -t tcp -p ":8887" -T kcp -P "x.s.s.d:2333" --kcp-key mypassword

2018/08/20 12:26:20 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:25 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:26 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:27 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:27 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:27 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:27 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:28 get out conn fail,read method reply fail,i/o timeout,retrying...
2018/08/20 12:26:30 get out conn fail,read method reply fail,i/o timeout,retrying...

**Comment by snail007** [comment]
your network maybe drop  encrypted udp traffic,try tls.

**Comment by joostshao** [comment]
./proxy http -t tcp -p ":8887" -T kcp -P "*:2333" --kcp-key mypassword
is ok now
