### ISSUE TITLE
windows端使用socks5转http（s）+socks5时出现问题

### ISSUE THREAD

**Issue by sjz123321** [snail007/goproxy#125]
当我在windows端使用socks5转http（s）+socks5时出现问题
服务端（VPS）执行了
proxy socks -t tls -p ":38080" -C proxy.crt  -K proxy.key
windows端执行了
proxy.exe socks -t tcp -p ":8080" -T tls -P "vps_ip:38080" -C proxy.crt -K proxy.key

使用chrome的socks5插件可以正常访问Google

使用sps协议转换（我重新解压了proxy工作目录） proxy sps -S socks -T tls -P 127.0.0.1:8080 -t tcp -p :18080 -C proxy.crt -K proxy.key

使用浏览器socks5代理调整为127.0.0.1:18080，提示new methods request fail,ERR: socks version not supported

调整系统代理为127.0.0.1:18080在原打开socks5的cmd终端中仍然提示socks version not supported

附日志：

sps端：

2018/08/24 15:08:16 use tls socks parent 127.0.0.1:8080
2018/08/24 15:08:16 tcp http(s)+socks proxy on [::]:18080
2018/08/24 15:08:40 connect clients4.google.com:443
2018/08/24 15:08:40 connect to tls parent 127.0.0.1:8080 fail, ERR:proxy: failed
 to write greeting to SOCKS5 proxy at clients4.google.com:443: EOF from 127.0.0.
1:53564
2018/08/24 15:08:40 connect clients4.google.com:443
2018/08/24 15:08:40 connect to tls parent 127.0.0.1:8080 fail, ERR:proxy: failed
 to write greeting to SOCKS5 proxy at clients4.google.com:443: EOF from 127.0.0.
1:53566
2018/08/24 15:08:51 connect mtalk.google.com:443
2018/08/24 15:08:51 connect to tls parent 127.0.0.1:8080 fail, ERR:proxy: failed
 to write greeting to SOCKS5 proxy at mtalk.google.com:443: EOF from 127.0.0.1:5
3568
2018/08/24 15:08:54 CONNECT:clients4.google.com:443
2018/08/24 15:08:54 connect clients4.google.com:443
2018/08/24 15:08:54 connect to tls parent 127.0.0.1:8080 fail, ERR:proxy: failed
 to write greeting to SOCKS5 proxy at clients4.google.com:443: EOF from 127.0.0.
1:53570
2018/08/24 15:08:54 CONNECT:clients4.google.com:443
2018/08/24 15:08:54 connect clients4.google.com:443
2018/08/24 15:08:54 connect to tls parent 127.0.0.1:8080 fail, ERR:proxy: failed
 to write greeting to SOCKS5 proxy at clients4.google.com:443: EOF from 127.0.0.
1:53572
2018/08/24 15:09:06 Received an interrupt, stopping services...
2018/08/24 15:09:06 accept error , ERR:accept tcp [::]:18080: use of closed netw
ork connection
2018/08/24 15:09:06 service sps stopped

socks端：

2018/08/24 15:08:28 blocked file loaded , domains : 4833
2018/08/24 15:08:28 direct file loaded , domains : 456
2018/08/24 15:08:28 use tls parent 45.76.28.198:38080
2018/08/24 15:08:28 tcp socks proxy on [::]:8080
2018/08/24 15:08:40 new methods request fail,ERR: socks version not supported
2018/08/24 15:08:40 new methods request fail,ERR: socks version not supported
2018/08/24 15:08:51 new methods request fail,ERR: socks version not supported
2018/08/24 15:08:54 new methods request fail,ERR: socks version not supported
2018/08/24 15:08:54 new methods request fail,ERR: socks version not supported
2018/08/24 15:09:07 Received an interrupt, stopping services...
2018/08/24 15:09:07 accept error , ERR:accept tcp [::]:8080: use of closed netwo
rk connection
2018/08/24 15:09:07 service socks stopped

**Comment by snail007** [comment]
使用错误:
windows端执行了
proxy.exe socks -t tcp -p ":8080" -T tls -P "vps_ip:38080" -C proxy.crt -K proxy.key
很明显8080是 -t tcp 没有加密的,但是:
proxy sps -S socks -T tls -P 127.0.0.1:8080 -t tcp -p :18080 -C proxy.crt -K proxy.key
你用sps转换的时候,连接8080却用了 -T tls 明显不对,应该是 -T tcp
