### ISSUE TITLE
为什么我使用简单的http代理，但是告诉我connect连接失败？

### ISSUE THREAD

**Issue by 1126912882** [snail007/goproxy#13]

**Comment by snail007** [comment]
提供详细步骤和日志输出才能排除原因。

**Comment by adaigit** [comment]
#  ./proxy http -t tcp -p "172.21.0.9:33080" -T tcp -P "192.168.228.129:80"
###该命令时在172.21.0.9机器执行的。。。。。。
2017/11/23 15:02:49 use tcp parent 192.168.228.129:80
2017/11/23 15:02:49 conn pool closed
2017/11/23 15:02:49 blocked file loaded , domains : 4833
2017/11/23 15:02:49 direct file loaded , domains : 456
2017/11/23 15:02:49 tcp http(s) proxy on 172.21.0.9:33080

//需求：让172.21.0.9（外网：123.206.64.116）机器代理192.168.228.129:80

在web访问123.206.64.116:33080报错：
2017/11/23 15:05:32 GET:/
2017/11/23 15:05:32 use proxy : true, 123.206.64.116:33080
2017/11/23 15:05:34 connect to 192.168.228.129:80 , err:dial tcp 192.168.228.129:80: i/o timeout,retrying...
2017/11/23 15:05:38 connect to 192.168.228.129:80 , err:dial tcp 192.168.228.129:80: i/o timeout,retrying...

是我哪里配置的不对么？

**Comment by snail007** [comment]
明显你用错了，你这是二级代理，你的一级代理配置了吗

**Comment by snail007** [comment]
你想要的是内网穿透
