### ISSUE TITLE
ssh版本不匹配

### ISSUE THREAD

**Issue by robbinhan** [snail007/goproxy#134]
```
SSH-2.0-OpenSSH_5.3
Protocol mismatch.
```
使用Transfer through SSH方式将http请却通过ssh代理出去，但是遇到协议版本不匹配的问题

**Comment by snail007** [comment]
请提供详细的使用情况.
1.客户端启动参数,日志.
2.服务器ssh情况.
这个ssh是用golang官方的ssh库,不应该出现协议不匹配的.
提供以上信息进一步排查.
