### ISSUE TITLE
增加功能：支持proxy服务以用户名或者访问的端口号来进行分流

### ISSUE THREAD

**Issue by jscrapy** [snail007/goproxy#135]
比如我有10根ADSL，我需要8888对应一号adsl, 9999对应2号。。。依此类推。
通过proxy服务绑定本地的某个网卡MAC地址的方式来启动，这样我就可以结合iptables来进行分流。
注意，我从8888端口进来的流量是要精确控制从1号adsl出去的，依此类推， ADSL一旦被重拨号，IP地址就发生了变化

squid也是只能支持绑定ip, 但是adsl拨号的ip是一直会变的。除此之外squid也不支持绑定网卡的MAC。
希望goproxy能有这个功能。

**Comment by snail007** [comment]
你说的功能十分特殊,目前应用层的程序是做不到绑定网卡的,只能是IP,操作系统也没有提供这样的接口.
