### ISSUE TITLE
内网穿透,非对称型NAT,出口IP有多个时候 连接不上

### ISSUE THREAD

**Issue by liyunde** [snail007/goproxy#137]
使用版本5.3和6.0都试过,效果是一样地
非对称型NAT网络里面
出口IP有多个时候,每次请求 IP 和端口都不一样
导致连接不上,一直打印
i/o timeout, retrying
换到IP 固定网络就可以连接上
请问,有没有解决方案,谢谢

**Comment by snail007** [comment]
goproxy解决不了这种底层网络问题，client和server需要需要能访问到bridge才能工作，这是基本前提。
