### ISSUE TITLE
Request: Add an option to let the parent proxy resolve hostnames if it can.

### ISSUE THREAD

**Issue by phantomcraft** [snail007/goproxy#144]
If the parent socks5/http proxy has builtin DNS resolution, instead of sending an external resolver like 8.8.8.8, why not just send the host name (such as github.com) to the proxy and ask it for resolve and return the IP?

Curl has this feature: https://curl.haxx.se/libcurl/c/CURLOPT_SOCKS_PROXY.html

Useful for use with Tor.

* Sorry for my bad English.

**Comment by snail007** [comment]
dns https://github.com/snail007/goproxy#8dns-anti-pollution-server

Tips: SOCKS5 proxy, support CONNECT, UDP protocol and don't support BIND and support username password authentication.

**Comment by phantomcraft** [comment]
What I mean is remote hostname resolution using the DNS servers of the proxy instead of passing an external resolver (8.8.8.8. 1.1.1.1 and others) to it.

**Comment by snail007** [comment]
in default , proxy using dns server of system to resolve hostbame，unless you passing --dns-address argument instead of system's dns
, client send whatever hostname proxy  will send  it
 to  parent as it is without resolution.
