### ISSUE TITLE
建议：添加对 WSS (WebSocket Secure) 的中间人劫持

### ISSUE THREAD

**Issue by LFODER** [snail007/goproxy#148]
希望更新能通过程序代理转发WSS协议，并能对WSS通讯内容进行监听与劫持。

**Comment by fufuok** [comment]
类似需求:
websocket(443) 反向代理, 我想把建立连接(101)后 websocket 传输的内容 debug 到日志, 现在有什么方法或思路么. 谢谢.

**Comment by snail007** [comment]
需要自己实现或者使用websocket协议库,劫持tls后实现握手和转发
