### ISSUE TITLE
这个可以和sstap搭配使用作为游戏加速吗

### ISSUE THREAD

**Issue by seven1orz** [snail007/goproxy#152]

**Comment by seven1orz** [comment]
sstap连接上了只有tcp转发，没有UDP转发

**Comment by snail007** [comment]
socks5支持udp，检查你的软件是否配置正确

**Comment by seven1orz** [comment]
客户端设置应该没有问题的，感觉是服务端没有UDP转发没有起来
![1](https://user-images.githubusercontent.com/43436676/46198969-4c495e00-c340-11e8-8f78-86747bd443c4.png)
![2](https://user-images.githubusercontent.com/43436676/46198971-4ce1f480-c340-11e8-8d4d-81f8fa871acc.png)
![3](https://user-images.githubusercontent.com/43436676/46198973-4ce1f480-c340-11e8-8415-ec82331aa934.png)

**Comment by snail007** [comment]
http代理不支持udp，基本常识。

**Comment by seven1orz** [comment]
尴尬，打扰了，我是小白。。
https://segmentfault.com/a/1190000016474170?tdsourcetag=s_pctim_aiomsg
参照这个做的，可以再浏览器用SwitchyOmega看youtube。
请问如果我要用socks5加速游戏还需要什么操作呢

**Comment by Vincen-31** [comment]
> 尴尬，打扰了，我是小白。。
> https://segmentfault.com/a/1190000016474170?tdsourcetag=s_pctim_aiomsg
> 参照这个做的，可以再浏览器用SwitchyOmega看youtube。
> 请问如果我要用socks5加速游戏还需要什么操作呢

请问您解决了吗 我用的是类似的Switchyomega浏览器插件和SStap 但是不知道如何在Switchyomega设置http或socks协议 因为sstap没有提供相应的端口，有办法解决吗，搜了好多都没有提过这个问题的。
