### ISSUE TITLE
socks5 fail

### ISSUE THREAD

**Issue by cole-dda** [snail007/goproxy#154]
./proxy socks --always -T ssh -P "192.168.0.2:22" -u root -D xxxxx  -t tcp -p "127.0.0.1:1080" 

开启socks5代理，但是客户端连接的时候，goproxy显示下面的异常

handshake fail, proxy: SOCKS5 proxy at cn.bing.com:80 has unexpected version 60

通过查看代码，可能是utils/socks/client.go 中处理错误了。
如果parent 是ssh，应该是直接访问，而不应该再使用socks5协议去访问了。

文档没有同步，如果是socks的，ssh的密码参数应该为"-D"而不是"-A"

**Comment by snail007** [comment]
使用错误，上级是ssh，上级不需要启动goproxy。仔细看手册。另外参数说明最新手册已经更正。
