### ISSUE TITLE
sps SOCKS5 转 SS 的时候某些协议不支持

### ISSUE THREAD

**Issue by DrayChou** [snail007/goproxy#157]
`/home/pi/go/bin/goproxy sps -S socks -T tcp -P 127.0.0.1:1081 -t tcp -p :18080 -h aes-192-cfb -j pass --forever --daemon --log /var/log/goproxy.log`

我使用上面的命令开启 socks5 转 ss 的代理，网页上访问 youtube 没有问题，但是在手机上用 youtube app 打开视频的时候，列表展示没有问题，但是展示视频的时候就会卡住。

猜测是手机 app 上某些协议不支持。

**Comment by snail007** [comment]
提供所有端启动命令和日志。
