### ISSUE TITLE
https无法代理

### ISSUE THREAD

**Issue by guozhen168** [snail007/goproxy#158]
我按照 [1.9 HTTP(S)反向代理](https://github.com/snail007/goproxy/blob/master/README_ZH.md#19-https%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86) 的配置进行设置，http可以正常使用，但是https不行

**Comment by snail007** [comment]
提供详细操作步骤好日志。

**Comment by guozhen168** [comment]
1、在可连外网的机器 A （IP为 `192.168.31.1`）起了proxy服务
`proxy.exe http -t tcp -p :80,:443`
2、内网机器 B（无法连外网，可连接 A），hosts 中配置配置需要连接的域名（如：`192.168.31.1 www.oschina.net`），这样配置完后，在 B 机器中可以 ping 通，但是无法访问。

**Comment by snail007** [comment]
日志

**Comment by snail007** [comment]
那就是没有请求进来，需要自己排查。

**Comment by guozhen168** [comment]
现在可以进入 proxy 了，原因是有个 VMware 的服务占用了 443 端口，下面是日志

`2018/10/17 21:34:20 decoder error , from 192.168.31.128:1716, ERR:http decoder data err:€O`
`2018/10/17 21:34:20 decoder error , from 192.168.31.128:1717, ERR:http decoder data line err:€.`

**Comment by snail007** [comment]
不是正确的https请求

**Comment by guozhen168** [comment]
用浏览器去访问的，还有不正确的https请求，难道代理还要设置https对应的证书？

**Comment by snail007** [comment]
客户端问题，自己排查，日志意思就是不是正确的https请求.

**Comment by todaygood** [comment]
> 1、在可连外网的机器 A （IP为 `192.168.31.1`）起了proxy服务 `proxy.exe http -t tcp -p :80,:443` 2、内网机器 B（无法连外网，可连接 A），hosts 中配置配置需要连接的域名（如：`192.168.31.1 www.oschina.net`），这样配置完后，在 B 机器中可以 ping 通，但是在浏览器无法访问 `https://www.oschina.net`无法访问

我觉得这个文档写得有问题， `proxy.exe http -t tcp -p :80,:443`  这是一个正向代理， 不是反向代理， 反向代理参见：

https://snail007.goproxyauth.com/goproxy/manual/zh/#/?id=_12http%e3%80%81https-%e7%bd%91%e7%ab%99%e5%8f%8d%e5%90%91%e4%bb%a3%e7%90%86
