### ISSUE TITLE
 proxy bridge cannot works

### ISSUE THREAD

**Issue by anke1460** [snail007/goproxy#162]
When i run  proxy bridge -p ":3390" -C proxy.crt -K proxy.key, use client to connect it and then will raise errors as follows:
read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range

**Comment by snail007** [comment]
need  more info , version , use --debug show  full log of bridge and client,and  how to use it.

**Comment by anke1460** [comment]
I use 6.2 version and the log show:
2018/10/26 11:07:39.086017 mux_bridge.go:168: server connection b20cf40eac619406768aa95af7b056188769b7ed default connected
2018/10/26 11:07:39.086230 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:07:42.086390 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:07:45.086573 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:07:48.086754 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:07:51.086925 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:07:54.087099 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:07:57.087290 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:00.087493 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:03.087676 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:06.087855 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:09.088020 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:12.088183 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:15.088355 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:16.686068 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.690372 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.691233 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.697818 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.698145 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.703623 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.704791 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.710088 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.710500 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:16.715066 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range
2018/10/26 11:08:18.088630 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:21.088808 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:23.370368 mux_bridge.go:154: read error,ERR:tls: first record does not look like a TLS handshake
2018/10/26 11:08:23.371281 mux_bridge.go:154: read error,ERR:tls: first record does not look like a TLS handshake
2018/10/26 11:08:24.088965 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:27.089162 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:30.089336 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:08:33.089538 mux_bridge.go:280: client default session not exists for server stream b20cf40eac619406768aa95af7b056188769b7ed, retrying...
2018/10/26 11:09:00.058096 mux_bridge.go:154: read error,ERR:read bytes fail ,err : runtime error: makeslice: len out of range

**Comment by anke1460** [comment]
In my server:

```
sudo proxy server -r ":81@:3001" -P "test.web.com:3390" -C proxy.crt -K proxy.key
proxy bridge -p ":3390" -C proxy.crt -K proxy.key
```

and local

`./proxy client -P "test.web.com:3390" -C proxy.crt -K proxy.key`

**Comment by snail007** [comment]
this is bug of v6.2,please use v6.3 which has fixed it.

**Comment by anke1460** [comment]
I have updated v6.4 or 6.3, but it still does not work, and it raise:
`mux_bridge.go:139: read error,ERR:tls: first record does not look like a TLS handshake`
