### ISSUE TITLE
macOS 版本的 goproxy 占用了大量的虚拟内存

### ISSUE THREAD

**Issue by moonfruit** [snail007/goproxy#163]
今天无意中发现，我在 macOS 10.14 上启动 goproxy 6.3 后立刻就占用了大量的（532G+）的虚拟内存空间。
但是平常使用中却没有发现有什么异常，硬盘也没有大量占用的迹象。但是其它的应用程序却不会有这种现象，所以我怀疑是不是还是哪里出了问题。
同时我在 CentOS 7.5 上却没有遇到相同的问题。

运行命令：
`ps -eO ppid,etime,pmem,rss,vsz | head -1; ps -eO ppid,etime,pmem,rss,vsz | grep goproxy`

在 macOS 上运行结果：
![image](https://user-images.githubusercontent.com/1070090/47421698-bde7c100-d7b3-11e8-8f73-d6b46866553e.png)

在 CentOS 上运行结果：
![image](https://user-images.githubusercontent.com/1070090/47421861-08693d80-d7b4-11e8-936f-d08b92eaea9c.png)

**Comment by snail007** [comment]
不用管虚拟内存，这是go的内存管理机制，对你物理内存没有影响。建议了解相关知识。所有go程序都是如此。

**Comment by snail007** [comment]
不用管虚拟内存，这是go的内存管理机制，对你物理内存没有影响。建议了解相关知识。所有go程序都是如此。

**Comment by moonfruit** [comment]
了解了，这个真是比较奇怪的特性。。。
