### ISSUE TITLE
客户端到服务器之间加了一层 GoProxy 端口转发，Nginx 怎么获取用户的真实 IP 地址？

### ISSUE THREAD

**Issue by designinlife** [snail007/goproxy#165]
GoProxy 版本：5.2 

使用的 TCP 端口映射转发请求。
./goproxy tcp -p 0.0.0.0:80 -T tcp -P 真实服务器IP地址:80 --forever --daemon

我的用法：客户端浏览器 -> GoProxy 服务端口 -> 真实 WEB 服务器 （Nginx）

目前的问题是：Nginx 只能拿到 GoProxy 所在的服务器IP地址  取不到客户端的真实IP地址。请教解决方法！

**Comment by snail007** [comment]
不支持。只能gp前面再加一个Nginx
