### ISSUE TITLE
最新版一个客户端请求会导致大量的连接，大量连接TIME_WAIT

### ISSUE THREAD

**Issue by bingyunxl** [snail007/goproxy#167]
服务端配置：
./proxy socks -t kcp -p ":13128" --forever --log proxy.log --daemon --kcp-mode "fast3" --kcp-method "salsa20" --kcp-key "mypassword"

客户端配置：
./proxy socks --forever --log proxy.log --daemon -t tcp -p ":1080" -T kcp -P "xxx.xxx.xxx.xxx:13128" --kcp-mode "fast3" --kcp-method "salsa20" --kcp-key "mypassword"

用curl访问： curl ip.cn

日志：
2018/10/29 22:59:30 conn 127.0.0.1:40968 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:40968 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:40972 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:40964 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:40974 - 104.16.24.88:80 connected
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:40984 - 104.16.24.88:80 connected
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:40928 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:40974 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:40986 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:40972 - 104.16.24.88:80 released
2018/10/29 22:59:30 conn 127.0.0.1:40928 - 104.16.24.88:80 released
2018/10/29 22:59:30 conn 127.0.0.1:40984 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:40992 - 104.16.24.88:80 connected
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:40994 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:40986 - 104.16.24.88:80 released
2018/10/29 22:59:30 conn 127.0.0.1:40994 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:41012 - 104.16.24.88:80 connected
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:41010 - 104.16.24.88:80 connected
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:41008 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:40992 - 104.16.24.88:80 released
2018/10/29 22:59:30 conn 127.0.0.1:41010 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:41020 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:41012 - 104.16.24.88:80 released
2018/10/29 22:59:30 conn 127.0.0.1:41008 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:41022 - 104.16.24.88:80 connected
2018/10/29 22:59:30 conn 127.0.0.1:41020 - 104.16.24.88:80 released
2018/10/29 22:59:30 use proxy true : 104.16.24.88:80
2018/10/29 22:59:30 conn 127.0.0.1:41032 - 104.16.24.88:80 connected

netstat命令查看网络连接：
tcp        0      0 192.168.1.148:52620     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44814         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:47824     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 192.168.1.148:58652     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 192.168.1.148:33804     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:39874         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:32980     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 192.168.1.148:40266     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:50774         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:38706     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:55768         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:50686     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 192.168.1.148:51116     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 192.168.1.148:49168     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:54016         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:50074         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:48648         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:54384     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 192.168.1.148:48930     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:55814         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:51364         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:37218         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:53398         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:37410         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:48842         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:55304     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:52226         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:38750     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:54908         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:59140     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:52298         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:42080         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:57036         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:38276         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:59580         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:40708     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:52482         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 192.168.1.148:49474     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 192.168.1.148:50366     104.16.24.88:80         TIME_WAIT   -                   
tcp        0      0 127.0.0.1:57412         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:47044         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44226         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:56008         127.0.0.1:1080          TIME_WAIT   -

**Comment by bingyunxl** [comment]
数据包转发使用redsocks

**Comment by snail007** [comment]
redsocks问题
