### ISSUE TITLE
转发到动态IP的问题

### ISSUE THREAD

**Issue by hejiadong0608** [snail007/goproxy#170]
使用的软件版本为6.4。
由于我使用的服务对带宽要求比较高，正好家里可以满足需求，所以用树莓派建立了这个服务。但是移动宽带连接到电信宽带非常不稳定，加上手里正好有几台腾讯云1M带宽的服务器，就拿来中转一下，达到稳定连接的目的。
因为家庭宽带都是动态IP，我用了域名来解决需要手动更换IP的问题，proxy的运行命令为：
proxy tcp -p ":10333" -T tcp -P "home.example.com:10333" --forever --daemon
现在的问题是，当IP有变化时，proxy那边就无法正常连接了，只能重启转发服务。
请问，有什么方法可以自动解决这个问题，谢谢。

**Comment by snail007** [comment]
这决定于系统dns更新时间，proxy解决不了dns问题。

**Comment by hejiadong0608** [comment]
您好！
根据我的判断，跟DNS应该没有关系。可能我的表达还不够清楚。
今天早上，运营商给我重新分配了IP地址。因为腾讯云的服务器在之后的几个小时里一直没有使用，所以我一直都不知道中转服务器已经连接不上了。到了下午四点多，才发现了这个问题。
此时我登陆到服务器，去ping我的域名，得到的是正确的IP地址，但是proxy的转发端口还是无法连接，必须结束进程，重新运行转发命令之后才能成功连接上。

**Comment by hejiadong0608** [comment]
@snail007

**Comment by mrshelly** [comment]
nginx 可以设置 dns cache 时间，所以转发时 做个 dns 查询就可以了，建议功能加上

**Comment by hktalent** [comment]
@hejiadong0608 启动，绑定IP、：
0.0.0.0
