### ISSUE TITLE
@snail007 希望支持ss代理&......

### ISSUE THREAD

**Issue by XYDsoft** [snail007/goproxy#171]
有几个Issues已经建议过支持ss了，我这里再啰嗦一下。群里也有不少人也提过。我觉得不支持ss制约了goproxy的发展。
我是个人来用，最常用的就是ss搭建和内网映射这个功能，但是每次都要借助于群主另外一个项目的工具完成ss，再用gp完成映射，好麻烦呀。而且还占用了有限的内存。
我看已经支持ss协议转换了，群主应该有了支持ss代理搭建和二级ss等计划，不知道下次更新以及接下来更新的Roadmap在哪，希望能够爆料下。
@snail007

**Comment by snail007** [comment]
现在就支持，看手册自己合理使用！

**Comment by zhfish** [comment]
恕我直言，有proxy还用什么ss。。。不过是缺少些生态而已

**Comment by XYDsoft** [comment]
@zhfish 其他人不知道，我们宿舍3同学，和我一样，用的游戏加速器就只支持ss。没办法
