### ISSUE TITLE
能否提供上下行流量和速率的相关log或者接口？

### ISSUE THREAD

**Issue by zhfish** [snail007/goproxy#174]
搭个梯子，两种方式：
1. 通过用户名密码认证，一个端口
2. 通过证书，需要每人一端口

问题有2:
1. 老大推荐哪种方式比较好？
2.无法知道每个人的使用情况，比如速率，已使用流量
小水管都是限流的，我怕谁用超了会影响所有人
老大能不能想办法支持一下？

**Comment by snail007** [comment]
不支持接口,日志,只支持针对tcp连接限速.

**Comment by zhfish** [comment]
如果我想自己扩展，从哪里入手呢？
