### ISSUE TITLE
如何结束deamon启动进程

### ISSUE THREAD

**Issue by daoiqi** [snail007/goproxy#177]
启动的话通过命令`./proxy @socks5_conf.txt --daemon`，但是没有找到如何停止程序。

只能ps | grep proxy 然后kill pid这样的方法吗？

没有 proxy stop ?类似的命令？

**Comment by LunacyZeus** [comment]
ps -ef|grep socks5_conf.txt|grep -v grep|cut -c 9-15|xargs kill -9 >/dev/null 2>&1

**Comment by daoiqi** [comment]
想象应该有 stop 命令，应该是能够记录pid，然后给pid发送kill信号
