### ISSUE TITLE
run service [socks] fail, ERR:socks servcie fail, ERR: err : open proxy.crt: The system cannot find the file specified.

### ISSUE THREAD

**Issue by FabioPLA** [snail007/goproxy#182]
![image](https://user-images.githubusercontent.com/26806814/48926160-62ba0300-ef06-11e8-8180-d4faeea3ebd1.png)
![image](https://user-images.githubusercontent.com/26806814/48926166-6c436b00-ef06-11e8-886d-62780f62bd79.png)我测试了两个版本的goproxy,都是显示找不到安全证书，看了很久，没想明白，谢谢！下面是我的操作步骤：
![image](https://user-images.githubusercontent.com/26806814/48926190-c3e1d680-ef06-11e8-89f3-86bfa0e52b52.png)
![image](https://user-images.githubusercontent.com/26806814/48926200-db20c400-ef06-11e8-9acf-5c69435cb8d8.png)
![image](https://user-images.githubusercontent.com/26806814/48926208-ea077680-ef06-11e8-9df7-b587376dd468.png)

**Comment by snail007** [comment]
看手册，生成证书。

**Comment by FabioPLA** [comment]
嗯嗯，我重新生成了一下证书，没用里面的自带证书就可以了
