### ISSUE TITLE
handshake fail, proxy: failed to write greeting to SOCKS5 proxy at static.xx.fbcdn.net:443: EOF

### ISSUE THREAD

**Issue by FabioPLA** [snail007/goproxy#184]
![image](https://user-images.githubusercontent.com/26806814/48995978-34962680-f185-11e8-9703-d76242443ec7.png)
![image](https://user-images.githubusercontent.com/26806814/48996162-09f89d80-f186-11e8-90ba-8437b23448e1.png)

![image](https://user-images.githubusercontent.com/26806814/48996023-63ac9800-f185-11e8-9c0d-edc1fe378961.png)
![image](https://user-images.githubusercontent.com/26806814/48996148-f3eadd00-f185-11e8-928d-157eab8f384d.png)
没想明白，在连接国外的服务器的时候，为什么会出现这样的状况？不清楚是不是socks版本的问题

**Comment by snail007** [comment]
所有端启动日志，命令。

**Comment by FabioPLA** [comment]
启动命令 ：  ./proxy socks -t tcp -p "192.168.3.5:8080" -T tls -P "47.244.17.247:33083" -
C proxy.crt -K proxy.key --log proxy.log
日志：
[proxy.log](https://github.com/snail007/goproxy/files/2614719/proxy.log)
浏览器chrome+SwitchyOmega 代理参数配置 socks5 192.168.3.5:8080

**Comment by snail007** [comment]
必须全部加密

**Comment by caidongyun** [comment]
handshake fail, proxy: failed to write greeting to SOCKS5 proxy at www.google.com:443: EOF

同样 换成sps就好了，是不是dns解析的问题？
