### ISSUE TITLE
认证的时候，在加了 -a handshake fail, ERR: none method found : Method_USER_PASS

### ISSUE THREAD

**Issue by FabioPLA** [snail007/goproxy#185]
国外代理服务器端的参数设置（Linux用的是源码编译的最新版本）：./goproxy socks -t tls -p :33086 -F auth-file.txt -T tcp -P 47.244.17.247:9150 -C proxy.crt -K proxy.key --always
![image](https://user-images.githubusercontent.com/26806814/49134863-0862dd00-f320-11e8-8b77-c38d6e18fd5a.png)

本地命令行的参数（本地的版本用的是6.1）：./proxy socks -T tls -P 47.244.17.247:33086 -F auth-file.txt -t tcp -p :8080
 -C proxy.crt -K proxy.key  --always
![image](https://user-images.githubusercontent.com/26806814/49135032-7f987100-f320-11e8-9840-3897be1cab9f.png)
请问这个问题出在？谢谢

**Comment by FabioPLA** [comment]
这个是认证文件的情况
![image](https://user-images.githubusercontent.com/26806814/49135115-bd959500-f320-11e8-810b-a6b1699633a3.png)

**Comment by yangjinhe** [comment]
认证只能用在最末端。比如你在最末端，提供了一个需要认证的socks或者http的代理。这里，你就可以用- a或者-F参数。

**Comment by snail007** [comment]
级联认证需求,可以参考sps功能

**Comment by ddyllen-z** [comment]
@snail007 我也是这个问题，但是我是没怎么看懂题主这个东西，他服务器，和本地都连了同一个ip。

我是这样的，服务器的命令：proxy socks -t tls -p "0.0.0.0:18085" -C ssl.crt -K ssl.key -a "myname:pwd" 

客户端：proxy socks -t tcp -p ":8080" -T tls -P "x.x.x.x:18085" -C ssl.crt -K ssl.key -a "myname:pwd"

按照文档说明，我没看出来我那里有错。

我一级代理开启tls和用户认证，二级代理连一级代理的时候也是开启tls加上一级代理需要的用户名密码。

是在没看出了哪里有问题呀。

**Comment by ddyllen-z** [comment]
我自己看命令help和测试，自己解决了。
我这种情况，二级代理的命令应该是：
proxy socks -t tcp -p ":8080" -T tls -P "x.x.x.x:18085" -C ssl.crt -K ssl.key -A "myname:pwd"
二级代连一级代理的认证参数是用-A不是-a，希望作者能在示例里面增加这样一个例子吧。
