### ISSUE TITLE
考虑增加--loglevel

### ISSUE THREAD

**Issue by XYDsoft** [snail007/goproxy#187]
由于控制台和写出的日志文件实在是太多了，不好阅读，也不便查阅和排查。

--loglevel= 设置输出日志的级别
<DEBUG | WARN | INFO | ERROR>
DEBUG为最低级别，将记录所有的日志输出；
ERROR为最高级别，仅仅记录错误状态的日志；

**Comment by XYDsoft** [comment]
>           由于控制台和写出的日志文件实在是太多了，不好阅读，也不便查阅和排查。
> --loglevel= 设置输出日志的级别
> <DEBUG | WARN | INFO | ERROR>
> DEBUG为最低级别，将记录所有的日志输出；
> ERROR为最高级别，仅仅记录错误状态的日志；

**Comment by vc1** [comment]
@snail007 提个小建议，增加代理等模块的详细访问日志功能，保存在服务端，商业版里能多个安全审计的卖点
