### ISSUE TITLE
kill 命令退出代码不为零

### ISSUE THREAD

**Issue by designinlife** [snail007/goproxy#188]
Received an interrupt, stopping services...
accept error , ERR:accept tcp 0.0.0.0:10001: use of closed network connection
service tcp stopped

goproxy 版本: 6.6
直接 kill 或 kill -s QUIT 时，报以上错误!

**Comment by snail007** [comment]
正常日志，不是错误。

**Comment by designinlife** [comment]
但是 exit code = 1, 这个貌似不好控制流程
比如：我要写个 Bash 脚本要判断是否正常退出

当然，关闭进程一般强杀也没啥事
