### ISSUE TITLE
SDK内存不释放，一直在占用，除非结束进程！

### ISSUE THREAD

**Issue by XYDsoft** [snail007/goproxy#193]
原来在我之前已经有很多人反应过这个问题了，sdk目前讲仅供测试功能可以，无法实际应用。stop后根本不释放内存，运行1天，自己一个人用也占用了大约1g多的内存，想stop然后再start下试试，结果发现服务是结束了，但是根本就是一丁点内存都不释放。

macOS的sdk没测试，其余sdk均测试了，版本为：6.6版本，以及未发布的6.7版本。

macOS 版本的 goproxy 占用了大量的虚拟内存 
#163 opened on Oct 24 by moonfruit  updated on Oct 24 

Windows版运行一天proxy.exe占用大约2g内存 
#80 opened on May 18 by cuiweieee  updated on May 22

**Comment by zhfish** [comment]
确实内存有些不释放的问题，我用的不是sdk，就是goproxy
端口转发功能，内存占用严重，我有台服务器挂上端口转发没管，大概半个月时间内存50%了，而这50%是吃满内存了
另一台及其挂的socks5和sps，大概一周时间吃满
目前用crontab每半天重启一次，倒是没什么影响

@snail007

**Comment by snail007** [comment]
开启debug模式，等内存上去，用kill -s sigup 结束进程，提供生成的5个prof文件和代理程序文件。
