### ISSUE TITLE
ip不走代理，已经用了always参数

### ISSUE THREAD

**Issue by kaala** [snail007/goproxy#195]
想通过代理访问ip地址

**Comment by pen9un** [comment]
@snail007 
遇到了同样的问题，请求帮助，谢谢
命令行参数为：
`proxy.exe http --always -t tcp -p "0.0.0.0:8090" -T tcp -P "10.10.9.20:30899" `
目标网址为：
`http://10.1x4.1x2.1x6/portal/`
日志：
![image](https://user-images.githubusercontent.com/20841959/52706395-4c30be80-2fc0-11e9-9e7a-78f6104f5da8.png)

试了-b blocked.txt参数，也不行，blocked.txt内容为：
`10.1x4.1x2.1x6`

**Comment by snail007** [comment]
内网地址默认直连，现在版本无法修改。

**Comment by snail007** [comment]
fixed in v7.6
