### ISSUE TITLE
建议内网穿透支持server、client、bridge使用不同的证书与密钥

### ISSUE THREAD

**Issue by muellerprecious** [snail007/goproxy#197]
三端使用相同的密钥存在安全风险，不建议在非安全通道上传输密钥。
希望可以支持三端分别使用本地生成的密钥进行通信，而不是把同一个密钥拷贝给三台电脑。

**Comment by yangjinhe** [comment]
你这个说法不对，请先理解这个密钥的作用。

**Comment by XYDsoft** [comment]
建议造锁的造个用什么钥匙都能打开的锁？
