### ISSUE TITLE
苹果手机使用http代理鉴权使用报错

### ISSUE THREAD

**Issue by binfer** [snail007/goproxy#199]
问题：
手机端iphoneX： goproxy设置auth认证后，部分网络无法正常使用，google.com无法搜索，qq信息可以接受。
（不使用auth时，不存在问题，一切正常）
电脑端mac： 一切正常。

错误信息：
RR:require auth header data
<img width="942" alt="image" src="https://user-images.githubusercontent.com/45391686/50390205-28df5500-076f-11e9-97fc-c030c7751d58.png">

**Comment by bigzs** [comment]
我的也是这个问题。IOS  12.1.2，鉴定也开了。

**Comment by bigzs** [comment]
而且不设用户密码，能连上但是，google.com也上不了
