### ISSUE TITLE
Support docker for mac

### ISSUE THREAD

**Issue by wweir** [snail007/goproxy#209]
Docker for Mac is a useful toolset, especially kubernetes support.

I use the goproxy transform socks5(go-shadowsocks2 with AEAD cipher) protocol into HTTP(s) proxy and set the HTTP proxy in docker for mac. Then deploy kubernetes in docker for mac, the docker hangs forever.

After that, I install shadowsocksX-ng which integrate proxioy as HTTP proxy tool, the kubernetes deployed correctly.

Then, I try docker pull k8s.gcr.io/pause-amd64:3.0 at these two networks environment, Wireshark shows the goproxy hangs a connection.

<img width="1325" alt="default" src="https://user-images.githubusercontent.com/2841254/51378075-5ee1e000-1b47-11e9-975f-f33c980fe093.png">

**Comment by hktalent** [comment]
@see https://github.com/fatedier/frp/issues/1056
@wweir

**Comment by wweir** [comment]
@hktalent Not the same problem.
My problem is docker pull image fail, not build docker images.
