### ISSUE TITLE
.i2p and .onion forwarding support?

### ISSUE THREAD

**Issue by whoizit** [snail007/goproxy#214]
like this for privoxy:
```
forward .i2p localhost:4444
forward-socks4a .onion localhost:9050 .
```
https://wiki.archlinux.org/index.php/Privoxy#i2p

**Comment by snail007** [comment]
it's decided of your browser setting proxy server supported or  not.

**Comment by whoizit** [comment]
But it's remote proxy, this localhost it's setting on remote proxy. I just set http://<my_remote_proxy_ip> to browser settings and I can get .i2p, .onion resources over remote proxy. So I haven't i2p/tor services on my PC

**Comment by snail007** [comment]
you can start a local goproxy as client of your remote parent proxy , browser's proxy setting using local goproxy

**Comment by whoizit** [comment]
it makes no sense

**Comment by snail007** [comment]
domains in blocked file  goproxy will  using parent access  them , read manual about blocked file.
