### ISSUE TITLE
setting outgoing IP

### ISSUE THREAD

**Issue by Pezhvak** [snail007/goproxy#215]
hi, i have thousands of IPv6 on my server, and i want to port a port on my IPv4 to a specific IPv6 for outgoing traffic, when i use --bind-listen it won't work as expected and i also want to specify the exact outgoing IP, is it possible? right now it will use IPv4 and IPv6 at the same time and it will ignore --bind-listen for IPv6.

please help

**Comment by snail007** [comment]
you can start two of goproxy,one of them is only listen on ipv6 and is the parent of other one and using bind listen argument, other one is the true proxies service, it's parent's address using ipv6 which is of  the local machine.

**Comment by Pezhvak** [comment]
i actually did that before opening this issue, let me share what i've done maybe something isn't right on my side.

the first instance of goproxy is like this:
proxy http -t tcp -p "[2a00:e60:7000:100:8000:0:edaf:8000]:8090" -B

the second one is like this:
proxy http -t tcp -p "0.0.0.0:38080" -T tcp -P [2a00:e60:7000:100:8000:0:e4d4:fcca]:8090

when i try to connect through IPv4:38080 it uses both ipv4 on my interface and also first IPv6 that is in ifconfig. completetly ignores -B flag or --bind-listen to use specified ipv6.

i've searched alot on google this library that you build is simply amazing with lots of features, i'm surprised why you didn't build an argument for specifying outgoing ip, is this possible for you to add? just having --bind-listen isn't enough it would't be perfect if something like --outgoing-ip gets added.

thanks you for putting your time to solve this issue

**Comment by snail007** [comment]
```
proxy http -t tcp -p "0.0.0.0:38080" -T tcp -P [2a00:e60:7000:100:8000:0:edaf:edaf]:8090 --always
```
in addition, if you access target domain or host is ipv4 ,bind listen won't be working,  because of system can't routing between ipv4 and ipv6 network.

**Comment by Pezhvak** [comment]
thank you for your fast response, actually i don't want them to be able to use ipv4, they should be able to only use ipv6. because it will get spammed if all of them use ipv4 which is only one, i'm about to use your library for hundreds of thousands of ipv6s on my server

**Comment by Pezhvak** [comment]
this didn't fix my issue but it seems to don't care

**Comment by sir-reynolds** [comment]
> this didn't fix my issue but it seems to don't care

thank you @Pezhvak 

I wanted to buy the commercial version of goproxy, but after seeing your problem, I gave up buying goproxy.

right now I asked someone to help look at this repository, then made a similar thing with some additional features such as:

1 # bind static outgoing ipv4 & ipv6
2 # bind random outgoing ipv6
3 # bind custom outgoing ipv6 from http header

with the third feature I can request outgoing ipv6 by only including the http header ip_exit: 2000:0:0:0:aaaa:bbbb:cccc:1

then goproxy will bind to 2000:0:0:0:aaaa:bbbb:cccc:1 and use it for outgoing ip

I paid him $ 750 for all of this
