### ISSUE TITLE
法律许可范围内提供完整的ss功能！

### ISSUE THREAD

**Issue by XYDsoft** [snail007/goproxy#219]
可以
使用-Country 参数指定国家。
例如 ss -Country EN .....
判断 参数不等于 "CN" ,则完整ss功能可用。
已经咨询过学法律的同学，在法律许可范围内。

很多人因为ss功能不完整或者太繁琐而放弃goproxy
goproxy也因此得不到更好的发展和传播
希望着重考虑支持完整独立的Shadowsocks，这对goproxy的发展和传播尤为重要。

**Comment by ddyllen-z** [comment]
我看还是算了吧，这个还是别扯法律了，没用。
别搞得到时大家都用不了了。
