### ISSUE TITLE
能否增加指定DNS？

### ISSUE THREAD

**Issue by js2854** [snail007/goproxy#22]
在非root权限下执行时，无法设置DNS的情况，某些网站无法打开，能否增加指定DNS的参数，来做域名解析？

**Comment by snail007** [comment]
dns请参考udp代理，手册3.4部分

**Comment by js2854** [comment]
感谢回复！答案并不是我想要的，我是想能够指定dns，用来解析走当前代理的域名，只是个小众需求。

**Comment by snail007** [comment]
http代理协议本来就是用远程服务器解析域名，要么就是你的客户端问题，建议用谷歌浏览器加插件。

**Comment by js2854** [comment]
是的，我遇到的场景就是一级http所在服务器的dns配置有问题，然后又是非root用户，所以改不了dns，导致如github无法访问。

**Comment by snail007** [comment]
明白了你的问题,目前还没有指定dns做为请求域名解析的功能.这个情况比较特殊.后续看需求量是否支持.

**Comment by js2854** [comment]
感谢！
