### ISSUE TITLE
最简单的二级代理，上级需要简单认证，如何配置？

### ISSUE THREAD

**Issue by zbutfly** [snail007/goproxy#220]
`proxy.exe http -t tcp -p ":33080" -T tcp -P "xxx.xxx.xxx.xxx:8080" --parent-auth="user:pass" --always`

报错：http不支持--parent-auth。

`proxy.exe http -t tcp -p ":33080" -T tcp -P "user:pass@xxx.xxx.xxx.xxx:8080" --always`

报错：user:pass无法连接

这个功能在手册里找不到。我司有代理，需要账号认证，而很多软件不支持带认证的http proxy，希望用goproxy转一下。

**Comment by snail007** [comment]
使用sps
