### ISSUE TITLE
goproxy UI建议与推荐

### ISSUE THREAD

**Issue by snail007** [snail007/goproxy#225]
首先感谢大家一直以来对goproxy的关注,接下来goproxy计划出一个web管理控制台,但是界面这个东西众口难调,加上作者审美XD,所以希望能够借助gp的粉丝们之手推荐一波你们认为好的管理界面,最好能提供链接方便查看,以及相关的建议.
最终会选出支持者做多的UI,也许你推荐的就是最后你使用的gp控制台UI哟.

有想法? 请在这里跟帖吧!

**Comment by adaiLinux** [comment]
简单、直观、易用

**Comment by Asuancaiyu** [comment]
layui 感觉还不错，扁平风

**Comment by ykfq** [comment]
- 符合目前主流的 UI 风格
- golang驱动、跨平台支持
- 框架参考  
  https://github.com/avelino/awesome-go#gui

**Comment by AlibabaDAMO** [comment]
web的ui前几个版本你应该随心所欲，后面的根据各种意见再优化。建议你能多听忠言，少听恭维的话。讽刺你的不一定是坏人，恭维你的也不一定是好人。建议你删减功能，着重发展内网穿透。一楼说的很对，简单才是根本，直观想必web就够直观了。同类项目不少，可以学习下成功项目的发展思路。恭喜goproxy又迎来一个新的开始！

**Comment by zjfsdnu** [comment]
我要求不高 跟frp的差不多就行

**Comment by yangjinhe** [comment]
做成向导式的，选项式的，不要像之前的gui一样，在窗口里面输命令。意义不大。

**Comment by CorePlusPlus** [comment]
adminlte(免费开源)  inspinia(收费) metronic(收费)

**Comment by Bunnyk001** [comment]
建议搞成和frp类似的那种,  那种的感觉就比较好

**Comment by reatang** [comment]
最简单的还是bootstrap吧

**Comment by wwek** [comment]
我觉得UI本身就是众口难调，所以功能只要易用都可以

**Comment by contineu0818** [comment]
**afsdfasdf** _adfdad_
![image](https://user-images.githubusercontent.com/24377663/61586049-7012b480-ab9d-11e9-98d6-f7428a7b4b49.png)
