### ISSUE TITLE
dns使用password会失败

### ISSUE THREAD

**Issue by momaer** [snail007/goproxy#226]
您好,请问 dns 不支持 password 吗?
vps上执行
./proxy socks -t tcp -p :33080 -z qq12345678
本地执行
./proxy dns -S socks -T tcp -Z qq12345678 -P vps_ip:33080 -p :2253
本地执行
dig @127.0.0.1 -p 2253 google.com.hk
失败.
vps报错如下:
2019/03/07 10:11:43 handshake fail, ERR: new methods request fail,ERR: socks version not supported
2019/03/07 10:11:48 handshake fail, ERR: new methods request fail,ERR: socks version not supported
2019/03/07 10:11:53 handshake fail, ERR: new methods request fail,ERR: socks version not supported
本地报错如下:
2019/03/07 10:11:43 dail to 8.8.8.8:53 fail,socks connect tcp vps_ip:33080->8.8.8.8:53: unexpected protocol version 119
2019/03/07 10:11:48 id: 60773 cache: MISS [(google.com.hk. IN A)]
2019/03/07 10:11:48 id: 60773 resolve: [(google.com.hk. IN A)] 8.8.8.8:53
2019/03/07 10:11:48 dail to 8.8.8.8:53 fail,socks connect tcp vps_ip:33080->8.8.8.8:53: unexpected protocol version 119
2019/03/07 10:11:53 id: 60773 cache: MISS [(google.com.hk. IN A)]
2019/03/07 10:11:53 id: 60773 resolve: [(google.com.hk. IN A)] 8.8.8.8:53
2019/03/07 10:11:53 dail to 8.8.8.8:53 fail,socks connect tcp vps_ip:33080->8.8.8.8:53: unexpected protocol version 119

如果vps执行的命令去掉 -z qq12345678 本地执行的命令去掉 -Z qq12345678 就可以正确解析域名.
请帮忙看下,谢谢.

**Comment by momaer** [comment]
本地和vps的版本是 v7.0_20190302172319

**Comment by snail007** [comment]
我使用最新版,本地测试-Z -z正常,检查你的网络是否阻止了加密流量

**Comment by snail007** [comment]
已经证实是bug.,下个版本7.2已经修复.
fixed in v7.2

**Comment by momaer** [comment]
感谢,比心
