### ISSUE TITLE
如何让程序强行在ipv4上监听端口

### ISSUE THREAD

**Issue by J-Cod3r** [snail007/goproxy#231]
vps上执行netstat查看发现程序只监听在tcp6上

**Comment by snail007** [comment]
那个显示是说明ipv6包含ipv4,你要绑定具体IP就写在参数里面。

**Comment by J-Cod3r** [comment]
客户端连接报这个错是什么原因？7.1版本   老版本没这个问题
[checker] 2019/03/11 11:02:38 check update fail, please check your network

**Comment by J-Cod3r** [comment]
> 那个显示是说明ipv6包含ipv4,你要绑定具体IP就写在参数里面。

按照你的方法确认绑定上了，但客户端连接报这个错是什么原因？7.1版本 老版本没出过这个问题
[checker] 2019/03/11 11:02:38 check update fail, please check your network

**Comment by snail007** [comment]
proxy必须可以访问网络

**Comment by J-Cod3r** [comment]
网络应该没问题，在没升级到7.1之前都是正常的，而且我在本地是可以telnet上服务器上proxy的端口的，请问这个客户端在连接的过程中是按什么条件判断网络有问题的？

**Comment by snail007** [comment]
proxy必须可以访问互联网
