### ISSUE TITLE
支持 多个二级代理 客户端

### ISSUE THREAD

**Issue by anime777** [snail007/goproxy#237]
同一个一级代理不支持 多个二级代理  作为客户端
重现步骤：
1. VPS开启一级代理   密码 --kcp-key mypassword
2.  本地PC1 开启二级代理   PC3通过此二级代理连接正常
3. 本地PC2 开启二级代理   PC3通过此二级代理连接失败
4. 关闭本地PC1二级代理  本地PC2 开启二级代理   PC3通过此二级代理连接恢复正常

**Comment by snail007** [comment]
端口冲突
