### ISSUE TITLE
Client每隔一分钟会断开一次。版本V7.2

### ISSUE THREAD

**Issue by linzhiqiang0514** [snail007/goproxy#239]
版本：V7.2，客户端，服务端都是
系统： cat /etc/redhat-release   CentOS release 6.10 (Final)

问题：
client端，每隔1分钟左右，自动重启。

日志如下：
2019/03/18 17:07:16.676598 config.go:513: worker ./proxy [PID] 30582 unexpected exited, restarting...
2019/03/18 17:07:21.677252 config.go:508: worker ./proxy [PID] 30606 running...
2019/03/18 17:07:21.761236 mux_client.go:78: use tls parent xxxxx:55555
2019/03/18 17:07:21.761493 mux_client.go:143: client started
2019/03/18 17:07:21.761549 mux_client.go:150: session worker[1] started
2019/03/18 17:07:21.761623 mux_client.go:150: session worker[2] started
2019/03/18 17:07:21.761712 mux_client.go:150: session worker[3] started
2019/03/18 17:07:21.761758 mux_client.go:150: session worker[4] started
2019/03/18 17:07:21.761798 mux_client.go:150: session worker[5] started
2019/03/18 17:07:21.761833 mux_client.go:150: session worker[6] started
2019/03/18 17:07:21.761863 mux_client.go:150: session worker[7] started
2019/03/18 17:07:21.761898 mux_client.go:150: session worker[8] started
2019/03/18 17:07:21.761928 mux_client.go:150: session worker[9] started
2019/03/18 17:07:21.761972 mux_client.go:150: session worker[10] started
2019/03/18 17:08:22.753138 config.go:513: worker ./proxy [PID] 30606 unexpected exited, restarting...
2019/03/18 17:08:27.753807 config.go:508: worker ./proxy [PID] 30626 running...
2019/03/18 17:08:27.833896 mux_client.go:78: use tls parent xxxxx:55555
2019/03/18 17:08:27.834213 mux_client.go:143: client started
2019/03/18 17:08:27.834236 mux_client.go:150: session worker[1] started
2019/03/18 17:08:27.834255 mux_client.go:150: session worker[2] started
2019/03/18 17:08:27.834272 mux_client.go:150: session worker[3] started
2019/03/18 17:08:27.834298 mux_client.go:150: session worker[4] started
2019/03/18 17:08:27.834322 mux_client.go:150: session worker[5] started
2019/03/18 17:08:27.834345 mux_client.go:150: session worker[6] started
2019/03/18 17:08:27.834368 mux_client.go:150: session worker[7] started
2019/03/18 17:08:27.834396 mux_client.go:150: session worker[8] started
2019/03/18 17:08:27.834420 mux_client.go:150: session worker[9] started
2019/03/18 17:08:27.834631 mux_client.go:150: session worker[10] started
2019/03/18 17:09:11.124166 mux_client.go:446: stream 8e7980f657e135f80eac9cad146b0396736776d6 created
2019/03/18 17:09:28.825846 config.go:513: worker ./proxy [PID] 30626 unexpected exited, restarting...
2019/03/18 17:09:33.826564 config.go:508: worker ./proxy [PID] 30645 running...
2019/03/18 17:09:33.909655 mux_client.go:78: use tls parent xxxxx:55555
2019/03/18 17:09:33.909958 mux_client.go:143: client started
2019/03/18 17:09:33.910004 mux_client.go:150: session worker[1] started
2019/03/18 17:09:33.910031 mux_client.go:150: session worker[2] started
2019/03/18 17:09:33.910047 mux_client.go:150: session worker[3] started
2019/03/18 17:09:33.910065 mux_client.go:150: session worker[4] started
2019/03/18 17:09:33.910089 mux_client.go:150: session worker[5] started
2019/03/18 17:09:33.910112 mux_client.go:150: session worker[6] started
2019/03/18 17:09:33.910135 mux_client.go:150: session worker[7] started
2019/03/18 17:09:33.910171 mux_client.go:150: session worker[8] started
2019/03/18 17:09:33.910195 mux_client.go:150: session worker[9] started
2019/03/18 17:09:33.910218 mux_client.go:150: session worker[10] started

**Comment by linzhiqiang0514** [comment]
不使用forever启动，输出如下：
[root@ffcs-crmtest10 proxy-7.2]# ./proxy client -P xxxx:55554 --debug    --log proxy2.log
[checker] 2019/03/18 17:54:40 check update fail, please check your network

经过沟通，是因为应用无法访问更新服务器导致的，

这个反而因为这个更新，导致服务无法正常运行，合理性上，还是希望作者考虑吧。

**Comment by nzai** [comment]
同样的版本同样的问题，检查更新失败就要退出代理吗？

**Comment by daoiqi** [comment]
感觉有点暴力呀，为什么一定要访问互联网呢？
