### ISSUE TITLE
请问两个问题，多谢

### ISSUE THREAD

**Issue by caonimac** [snail007/goproxy#25]
1 这个能在debian软路由上透明代理吗？
2 中转ssh是不是不支持udp啊？如果是那就相当于ssh -D啊，没有意义了啊。

**Comment by snail007** [comment]
1.不支持透明代理,透明代理可以结合redsocks+proxy的socks5代理实现.
2.ssh中转就是实现ssh的-D功能,所以ssh中转模式的socks5代理不支持udp协议.
