### ISSUE TITLE
ss功能不支持readme写的一些加密参数

### ISSUE THREAD

**Issue by kpivy8** [snail007/goproxy#253]
aes-128-gcm , aes-192-gcm ,aes-256-gcm , chacha20-ietf-poly1305，这几个协议经测试是不支持的

**Comment by snail007** [comment]
我测试都是没问题的，不知道你是怎么测试的，用的什么软件，我测试用的是安卓ssr。

**Comment by kpivy8** [comment]
不好意思，忘记写上测试命令了，命令如下：
./proxy sps -S ss -H aes-128-gcm -J passwd -T tcp -P 192.168.1.25:3306 -t tcp -p :666

**Comment by snail007** [comment]
使用错误，仔细看手册，你那是设置上级密码和加密。

**Comment by kpivy8** [comment]
好的， 谢谢
