### ISSUE TITLE
Maybe a bug in socks proxy process when using tcp without authentication in backend.

### ISSUE THREAD

**Issue by sddwt** [snail007/goproxy#254]
During socks5 proxy progress, we tested for serval auth situations,
In this 👇 section , A is the front server as downstream, so B is the backend server as upstream.

|                  A                |                      B                     |
|----------------------- |--------------------------------|
|     A is encrypted      |        B is none encrypted       |
| A is none encrypted |        B is encrypted                |
|    A is encrypted       |        B is encrypted                |

**SO, whatever I tested using command such as:**
- **a**  ./proxy socks -t tcp -p "0.0.0.0:1080" -T tcp -P "B:1080" -g "A"
- **b** ./proxy socks -t tcp -p "0.0.0.0:1080" -T tcp -P "B:1080" -g "A" --auth-url "http://AUTH_URL/account.cgi"
In the **a** command, I can input any user & pass. I can not use udp proxy due to wrong password , but I can use tcp well.
In the **b** command, I can not input anything except the correct user and pass, but My tcp and udp proxy IP shows the server A's.
**Why I am doing this:**
IF B server would down I can change it easily due to domain host name , but I require user/pass to let out stuff have access to server.
**What I want to improve:**
I want to Use Correct account to send proxy requests , not just verify users when they go through the UDP but also TCP.

**Comment by sddwt** [comment]
Thank you for your precious time and value!
:)
👍

**Comment by snail007** [comment]
you should using function sps instead of that.Fully access control is supported by the  sps.

**Comment by snail007** [comment]
in your case,you should noticed argument with --always

**Comment by sddwt** [comment]
First of all, It's very useful, I haven't read manual carefully, I appreciate it.
But I noticed that sps will open http(s) & socks5.
Is there any var to specific only socks5 ?
Thanks again.

**Comment by snail007** [comment]
you can disable each  of http(s) \ss \sockks with --disable-xxx,
reading outputting of `proxy  help  sps`
