### ISSUE TITLE
fail2ban integration

### ISSUE THREAD

**Issue by mhf-ir** [snail007/goproxy#256]
Any guide for fail2ban integration?

**Comment by snail007** [comment]
read manual about keyword： stop

**Comment by mhf-ir** [comment]
pardon, did you mean stop domains? that's not i'm looking for.

Looking for fail authentication and block them via iptables using fail2ban. 
https://www.linode.com/docs/security/using-fail2ban-for-security/#write-a-regex-for-fail2ban

**Comment by snail007** [comment]
not supported currently
