### ISSUE TITLE
一直报：check update fail, please check your network错误

### ISSUE THREAD

**Issue by huangyy** [snail007/goproxy#258]
如何关闭update检查？

**Comment by snail007** [comment]
不能关闭，proxy必须可以访问互联网，如果在内网可以设置http_proxy环境变量。

**Comment by huangyy** [comment]
机器本身访问互联网没问题啊，而且，前2天还一切正常。就是从昨天开始，一直报这个错误。

**Comment by snail007** [comment]
提供你的外网IP

**Comment by pkptzx** [comment]
我也提示这个,但明明能上网...

**Comment by AlexanderZhan** [comment]
我了遇到了，太霸道了，有没有捣鬼哦！

**Comment by recall704** [comment]
我也遇到了，暂时用了老版本

**Comment by xtso520ok** [comment]
已经验证，机器本身需要支持resolv。估计是留给proxy这个程序使用的

**Comment by recall704** [comment]
@xtso520ok 支持resolv 是什么意思？

**Comment by Villivateur** [comment]
我也遇到这个问题了，而且报错后程序会自动退出。
环境: Ubuntu 16.04
公网访问没有问题

**Comment by feixuelove** [comment]
开始正常 现在阿里云上的都是不行的 都是提示 [checker] 2019/05/14 19:17:46 check update fail, please check your network

**Comment by zone009** [comment]
为啥非要加这个限制？内网环境没公网运行不了咋办，感觉很恶心啊

**Comment by hawktang** [comment]
请问哪里有老版本

**Comment by recall704** [comment]
> 请问哪里有老版本, 现在这样没办法用啊.

之前我 fork 过
