### ISSUE TITLE
source code ?

### ISSUE THREAD

**Issue by boianmihailov** [snail007/goproxy#260]
Where is the actual source for v7.3 ? 
Repo seems to contain 3.0 and lacks the options available in the binaries. 

Great job, btw!

**Comment by UrielCh** [comment]
your proxy look awsome, but the source code do not match the binary.

**Comment by UrielCh** [comment]
you can check the source code from:
https://gitlab.com/czoo00/goproxy/
it's still not the right version but it's more up to date.

**Comment by UrielCh** [comment]
from the README:

### Source code declaration

The author of this project found that a large number of developers based on the project for secondary development or using a large number of core code of the project without complying with the GPLv3 agreement, which seriously violates the original intention of using the GPLv3 open source agreement in this project. In view of this situation, the project adopts the source. The code delays the release strategy, to a certain extent, to curb these behaviors that do not respect open source and do not respect the labor results of others.
This project will continue to update the iterations, and continue to release the full platform binary program, providing you with powerful and convenient proxy tools.
If you have customized, business needs, please send an email to `arraykeys@gmail.com`

**Comment by boianmihailov** [comment]
I've read that, yet I am having trust issues. 
So if the License says GPLv3, but the author is not releasing sources ... thank god Linus Torvalds is not feeling the same about "secondary development"

**Comment by UrielCh** [comment]
All the sources had been removed 4 month ago, and the news version deny launch inside a secured container.
[issue 263](https://github.com/snail007/goproxy/issues/263).

`lastest version of goproxy can't running in docker`

May be you should not use this software outside of china mainland...

**Comment by YanzheL** [comment]
> I've read that, yet I am having trust issues.
> So if the License says GPLv3, but the author is not releasing sources ... thank god Linus Torvalds is not feeling the same about "secondary development"

Truly agree. It's a shame that this project is ruined by this dishonest behavior. Really sucks.

**Comment by brlin-tw** [comment]
To be fair regardless of the license of the code declared to be the author/copyright holder has the right to determine whether or not to release the source code of (part) of their software.  Intellectual licenses are for restricting third parties' behavior instead of the authors'.

Though I still hope that:

* The current public code remains to be buildable and at least partially usable.
* The old releases on the project site are preserved.

**Comment by shaxiaozz** [comment]
I used go build to compile the output. Enter: ```goproxy http --help```, which lacks many parameter options.

Using ```goproxy --version```, I got 3.0, which seems to indicate that this repository is not a complete code
