### ISSUE TITLE
v7.3源码编译和install_auto.sh安装的v7.3不一致

### ISSUE THREAD

**Issue by wangchengdg** [snail007/goproxy#262]

**Comment by wangchengdg** [comment]
需要使用【HTTP二级代理(加密)】，在公网两个vps都使用install_auto.sh安装，能实现正常的http代理功能。
一个使用公网install_auto.sh安装S1，一个本地编译L1，浏览器通过本地代理L1连到S1，发现S1出现解密错误“decoder error , from my_ip_addr:64374, ERR:http decoder read err:remote error: tls: bad certificate”，查看配置参数，发现S1上的版本有-z和-Z参数，但是源码中没有该参数，所以判断S1上的版本和源码编译的不是同一个版本，虽然版本号相同。

**Comment by wangchengdg** [comment]
L1和S1使用的是相同的证书

**Comment by snail007** [comment]
仔细看：项目源码申明

**Comment by wangchengdg** [comment]
了解
