### ISSUE TITLE
goProxy not working instide an Docker container.

### ISSUE THREAD

**Issue by UrielCh** [snail007/goproxy#263]
Hi,

When I pack snail007/goproxy inside a docker container, it spot working, with no error message.

**Dockerfile**
```Dockerfile
FROM golang as builder
WORKDIR /root/
RUN FILE=proxy-$(go env GOOS)-$(go env GOARCH).tar.gz && \
    wget https://github.com/snail007/goproxy/releases/download/v7.3/$FILE -O $FILE && \
    tar -xvzf $FILE && \
    rm $FILE

FROM alpine
WORKDIR /root/
COPY --from=builder /root/* /root/
ENTRYPOINT [ "/root/proxy" ]
```

test it:

```bash
docker build -f Dockerfile  -t goproxy .
docker run -it --rm goproxy --help
```

I'ts work if I build snail007/goproxy from git, but it's look to be an old version.

**Comment by snail007** [comment]
lastest version of goproxy can't running in docker

**Comment by UrielCh** [comment]
Is that possible to download an old version ?

I have just migrate to docker. and I'm running everything inside containers.
