### ISSUE TITLE
windows上安装proxy，让局域网的linux可以通过windows proxy访问google

### ISSUE THREAD

**Issue by baiwfg2** [snail007/goproxy#266]
hi. 我的需要是这样的：

我windows是公司的，自动配置了可以访问google。但虚机下的linux不行。我现在希望通过在linux上配置http_proxy/https_proxy环境变量，让它指向windows配好的proxy，这样linux http/https请求都可由windows发到互联网上。

不知这样的需求goproxy能否实现？

多谢！

**Comment by snail007** [comment]
Windows安装普通一级代理即可,不过windows要保证一级代理可以访问google.

**Comment by pkptzx** [comment]
虚拟机就没这个必要用goproxy了......好好学学虚拟机的网络吧...

**Comment by baiwfg2** [comment]
也不一定是虚拟机了，我在泛指远程的linux host。不过刚发现IDC与办公网之间有隔离，要提出申请才行。多谢两位。
