### ISSUE TITLE
linux-amd64执行不了

### ISSUE THREAD

**Issue by LincolnBruce** [snail007/goproxy#268]
![image](https://user-images.githubusercontent.com/7814560/56780605-8fa27700-6812-11e9-8a70-c7dcf63ee90c.png)
./proxy根本me没有响应啊。。。。
```shell
/proxy-linux # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.2
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by LincolnBruce** [comment]
![image](https://user-images.githubusercontent.com/7814560/56780808-58809580-6813-11e9-82df-fe51d34467c0.png)
ubuntu也不行

**Comment by newzf** [comment]
curl -L https://raw.githubusercontent.com/snail007/goproxy/master/install_auto.sh | bash  
 64位机用上面的指令安装就行了

**Comment by LincolnBruce** [comment]
ok 我试一试

**Comment by tidaybreak** [comment]
centos7.2 docker 上运行没反映 跑了curl -L https://raw.githubusercontent.com/snail007/goproxy/master/install_auto.sh | bash也一样

**Comment by YanzheL** [comment]
在Ubuntu 18.04上用
```shell
curl -L https://raw.githubusercontent.com/snail007/goproxy/master/install_auto.sh | bash
```
安装完了之后
```shell
proxy help
```
没有任何输出，也没报错

**Comment by pinghe** [comment]
@snail007  下个版本能恢复支持在docker中运行吗？

**Comment by LincolnBruce** [comment]
@pinghe 我的都是在docker中运行的都不行
