### ISSUE TITLE
使用sps转发后。服务一直监听在ipv6，如何让程序监听在ipv4上

### ISSUE THREAD

**Issue by xiezhm** [snail007/goproxy#269]
启动命令：./proxy sps -S ss --lb-method=leastconn --lb-onlyha -t tcp -p :18787，服务器上只是显示在
![image](https://user-images.githubusercontent.com/30453707/57271268-6e1e7680-70c1-11e9-9195-ba8a2749213f.png)

如何才能同时也显示在ipv4上监听。

**Comment by Ostaer** [comment]
这个监听就是支持ipv4和ipv6连接的

**Comment by tocrafty** [comment]
把防火墙关了试试
