### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pinghe** [snail007/goproxy#271]
7.3 7.4 has this problem

http(s) conn handler crashed with err : runtime error: invalid memory address or nil pointer dereference
stack: goroutine 4879 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/snail007/proxy/services/http.(*HTTP).callback.func1()
        /home/go/src/github.com/snail007/proxy/services/http/http.go:347 +0x57
panic()
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/snail007/proxy/services/http.(*HTTP).OutToTCP()
        /home/go/src/github.com/snail007/proxy/services/http/http.go:458 +0x5ab
github.com/snail007/proxy/services/http.(*HTTP).callback()
        /home/go/src/github.com/snail007/proxy/services/http/http.go:394 +0x4f6
github.com/snail007/proxy/core/cs/server.(*ServerChannel).ListenTCP.func1.2()
        /home/go/src/github.com/snail007/proxy/core/cs/server/server.go:163 +0x60
created by github.com/snail007/proxy/core/cs/server.(*ServerChannel).ListenTCP.func1

**Comment by snail007** [comment]
show full command of starting

**Comment by pinghe** [comment]
····
./proxy http --always -t tcp -p ":1080" -T tls -P "vpshost:1080" -C proxy.crt -K proxy.key -b proxy_blocked -d proxy_direct --forever --log proxy.log --daemon --jumper http://myhttpproxyhost:80
····

**Comment by snail007** [comment]
your error info seems like proxy version of 7.3, please using 7.4 and show me details about logging.

**Comment by pinghe** [comment]
7.4

```
http(s) conn handler crashed with err : runtime error: invalid memory address or nil pointer dereference
stack: goroutine 4063 [running]:
runtime/debug.Stack
        /usr/local/go/src/runtime/debug/stack.go:24 
github.com/snail007/proxy/services/http.(*HTTP).callback.func1()
        /home/go/src/github.com/snail007/proxy/services/http/http.go:347 
panic()
        /usr/local/go/src/runtime/panic.go:522 
github.com/snail007/proxy/services/http.(*HTTP).OutToTCP()
        /home/go/src/github.com/snail007/proxy/services/http/http.go:458 
github.com/snail007/proxy/services/http.(*HTTP).callback()
        /home/go/src/github.com/snail007/proxy/services/http/http.go:394 
github.com/snail007/proxy/core/cs/server.(*ServerChannel).ListenTCP.func1.2()
        /home/go/src/github.com/snail007/proxy/core/cs/server/server.go:163 
created by github.com/snail007/proxy/core/cs/server.(*ServerChannel).ListenTCP.func1
        /home/go/src/github.com/snail007/proxy/core/cs/server/server.go:157 
```

**Comment by snail007** [comment]
bug已经确认，下个版本修复。

**Comment by pinghe** [comment]
v7.5

```
2019/06/11 01:16:14 forever ./proxy [PID] 4372 running...
2019/06/11 01:16:14 worker ./proxy [PID] 4381 running...
2019/06/11 01:16:14 blocked file loaded , domains : 4833
2019/06/11 01:16:14 direct file loaded , domains : 456
2019/06/11 01:16:14 use tls parent [myvps.com:80] [ ROUNDROBIN ]
2019/06/11 01:16:14 tcp http(s) proxy on [::]:80


2019/06/11 01:17:19 worker ./proxy [PID] 4381 unexpected exited, restarting...
What's going on


2019/06/11 01:17:24 worker ./proxy [PID] 4817 running...
2019/06/11 01:17:24 blocked file loaded , domains : 4833
....


```

**Comment by snail007** [comment]
use  --log ，get logging of worker。

**Comment by pinghe** [comment]
https://github.com/snail007/goproxy/issues/271#issuecomment-492985437

already has --log

**Comment by snail007** [comment]
show the full logging

**Comment by pinghe** [comment]
```
2019/06/11 03:58:01 worker ./proxy [PID] 19745 running...
proxy free version 7.5  by snail , email : arraykeys@gmail.com
2019/06/11 03:58:01 blocked file loaded , domains : 4833
2019/06/11 03:58:01 direct file loaded , domains : 456
2019/06/11 03:58:01 use tls parent [myvps:80] [ ROUNDROBIN ]
2019/06/11 03:58:01 tcp http(s) proxy on [::]:80
2019/06/11 03:59:06 check update fail, please check your network
2019/06/11 03:59:06 worker ./proxy [PID] 19745 unexpected exited, restarting...
2019/06/11 03:59:11 worker ./proxy [PID] 20185 running...
proxy free version 7.5  by snail , email : arraykeys@gmail.com
2019/06/11 03:59:12 blocked file loaded , domains : 4833
2019/06/11 03:59:12 direct file loaded , domains : 456
2019/06/11 03:59:12 use tls parent [myvps:80] [ ROUNDROBIN ]
2019/06/11 03:59:12 tcp http(s) proxy on [::]:80
```

```
curl -x myhttpproxyhost:80 http://www.apache.org

It returned 200
```

**Comment by snail007** [comment]
check update fail, please check your network，your server must can be access Internet network

**Comment by pinghe** [comment]
my server can access Internet network.

client
```
curl -x myhttpproxyhost:80 http://www.apache.org

It returned 200
```

vpshost
```
curl  http://www.apache.org

It returned 200
```

**Comment by snail007** [comment]
try : `curl https://lic00.host900.com` on your server.

**Comment by pinghe** [comment]
[z.txt](https://github.com/snail007/goproxy/files/3275043/z.txt)

**Comment by snail007** [comment]
it seems your public IP is blocked by cloudflare, can you show me the IP, and i add it to whitelist.
