### ISSUE TITLE
内网穿透ssh,使用xshell登陆不了,crt可以登陆

### ISSUE THREAD

**Issue by onlonely** [snail007/goproxy#273]
我搭建了个内网穿透,穿透内网的ssh服务
使用xshell6 build0115无法连接登陆服务器,有提示Connection established.
表明连接是建立了.应该是有什么规范没有遵守,,但是不使用内网穿透,使用xshell是可以正常登陆的

并且如果使用SecureCRT 8.3.0 (x64 build 1514)就可以正常内网穿透后ssh登陆

**Comment by snail007** [comment]
xshell问题
