### ISSUE TITLE
Stop all but one (or two) domains

### ISSUE THREAD

**Issue by ejdoh1** [snail007/goproxy#275]
I have a simple use-case where I want to allow access to a single domain and stop all other requests.
How do I achieve this?

**Comment by snail007** [comment]
see also #247

**Comment by ejdoh1** [comment]
Thanks - missed it as the duplicate was not in English.

Also, I was looking for where the 'stop' argument is handled but couldn't see it in [config.go](https://github.com/snail007/goproxy/blob/v7.4/config.go).

Am I missing something?

**Comment by snail007** [comment]
https://github.com/snail007/goproxy#source-code-declaration

**Comment by ejdoh1** [comment]
Ah I see - makes it hard to contribute.

Good luck with your project
