### ISSUE TITLE
check update fail

### ISSUE THREAD

**Issue by mj520** [snail007/goproxy#276]
proxy free version 7.2  by snail , email : arraykeys@gmail.com
2019/05/26 22:08:44 use tcp parent r-bp1a8406a7fc0434.redis.rds.aliyuncs.com:6379
2019/05/26 22:08:44 tcp proxy on 0.0.0.0:6379
[checker] 2019/05/26 22:08:48 check update fail, your application must be update to lastest version

1 建议文档加说明 没有关于检查描述
2 建议增加是否检查新版，如果检查新版是否考虑能自动更新，不能更自动更新 没人每天在内外网服务器进行查看
3 建议保留历史版本，新版有bug时可以用老版本
4 强行版本检查 对应使用 不方便，上次升级新版表示后悔。。。。。

**Comment by bladethirst** [comment]
在内网使用，不能连接互联网，我也遇到同样的问题。。。

**Comment by hampsterx** [comment]
nice project but doing phone home sounds a bit dodgy :(

**Comment by wangwanqiang** [comment]
给的方案根本解决不了问题。因为外网的服务器不是我们自己搭的，控制不了。外网也不是用的这个软件做的代理。

**Comment by leizongmin** [comment]
遇到同样问题，可怕

**Comment by snail007** [comment]
#286
