### ISSUE TITLE
2019/05/30 09:53:59 check update fail, please check your network

### ISSUE THREAD

**Issue by healthly** [snail007/goproxy#280]
昨天还行，今天又歇菜了，update 的地址是多少呀？
2019/05/30 10:01:20 CONNECT:chat-pa.clients6.google.com:443
2019/05/30 10:01:23 CONNECT:chat-pa.clients6.google.com:443
2019/05/30 10:01:23 CONNECT:chat-pa.clients6.google.com:443
2019/05/30 10:01:23 CONNECT:chat-pa.clients6.google.com:443
2019/05/30 10:01:23 use proxy : true, chat-pa.clients6.google.com:443
2019/05/30 10:01:26 use proxy : true, chat-pa.clients6.google.com:443
2019/05/30 10:01:26 use proxy : true, chat-pa.clients6.google.com:443
2019/05/30 10:01:26 use proxy : true, chat-pa.clients6.google.com:443
2019/05/30 10:01:32 CONNECT:play.google.com:443
2019/05/30 10:01:35 use proxy : true, play.google.com:443
2019/05/30 10:01:37 check update fail, please check your network

**Comment by healthly** [comment]
补充一下，刚才试了，同一个出口网络下，windows和Linux是正常的，macOS 10.14.5 有上述问题

**Comment by cmcm951102** [comment]
不能更新就停止运行？？？！！我想在内网用一下不行吗？这设计怎么想的……

**Comment by m2acgi** [comment]
推荐 gost, 功能。7.1 之前一直用的这个，后来有人违反开源协议盗用代码，作者就作了很大的改动，现在强制升级版本，代码方面也基本是闭源了。

**Comment by rabbixMq** [comment]
@cmcm951102 是啊，时好时坏的，关键的时候不能用，很着急。希望作者改改

**Comment by snail007** [comment]
v7.6已经优化这块

**Comment by healthly** [comment]
今天彻底不能用了，服务端也有问题
2019/06/24 11:26:07 check update fail, <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | lic00.host900.com used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />

**Comment by moonfruit** [comment]
可不可以加个选项禁用掉更新检查啊？或者检查失败打个 warning 不要强制退出啊

**Comment by snail007** [comment]
> 今天彻底不能用了，服务端也有问题
> 2019/06/24 11:26:07 check update fail,
> 
> <title>Access denied | lic00.host900.com used Cloudflare to restrict access</title>

IP存在攻击行为，提供IP核实。

**Comment by moonfruit** [comment]
我也彻底不能用了，我只是需要同时启动20个左右的实例，这样就被判断为有攻击行为是不是太严格了？
我现在的 IP 是 101.224.45.227

**Comment by snail007** [comment]
#286
