### ISSUE TITLE
ver7.5在windows server 2003 上运行报错（v6.x版本正常）

### ISSUE THREAD

**Issue by Schr0dingerCat** [snail007/goproxy#284]
终端下输出的错误信息：

F:\proxy-windows-386>proxy.exe http -t tcp -p "0.0.0.0:38080"
proxy free version 7.5  by snail , email : arraykeys@gmail.com
2019/06/21 14:19:33 err : run service [http:http] fail, ERR:http servcie crashed
, ERR: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Th
e specified procedure could not be found.
trace:goroutine 1 [running]:
runtime/debug.Stack(0x1186c8b4, 0x96cd40, 0x118ffe80)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x83
github.com/snail007/proxy/services.Run.func1(0x1184c090, 0x4, 0x1186cea0)
        /Users/go/src/github.com/snail007/proxy/services/service.go:58 +0x42
panic(0x96cd40, 0x118ffe80)
        /usr/local/go/src/runtime/panic.go:522 +0x165
syscall.(*LazyProc).mustFind(0x1183f9e0)
        /usr/local/go/src/syscall/dll_windows.go:311 +0x42
syscall.(*LazyProc).Addr(0x1183f9e0, 0xf20420)
        /usr/local/go/src/syscall/dll_windows.go:318 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x750, 0x9, 0x1186c97c, 0x
8, 0x3, 0x1181d348)
        /usr/local/go/src/internal/syscall/windows/zsyscall_windows.go:353 +0x27

os.newFileStatFromGetFileInformationByHandle(0x9ecef6, 0x4, 0x750, 0x0, 0x9ecef6
, 0x4)
        /usr/local/go/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x1191d388, 0xa15698, 0x1191d388, 0x0, 0x1191d388)
        /usr/local/go/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x9ecef6, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:62 +0xac
github.com/snail007/proxy/utils.LoadFileToMap(0x9ecef6, 0x4, 0x2e, 0x63, 0x6f, 0
x6d, 0xa, 0x0, 0x0, 0x0)
        /Users/go/src/github.com/snail007/proxy/utils/functions.go:905 +0x6c
github.com/snail007/proxy/services/http.(*HTTP).CheckArgs(0x11912600, 0x0, 0x0)
        /Users/go/src/github.com/snail007/proxy/services/http/http.go:127 +0xcd1

github.com/snail007/proxy/services/http.(*HTTP).Start(0x11912600, 0x9e3f20, 0x11
8c08c0, 0x11876a20, 0x1186cea0, 0x1191d301)
        /Users/go/src/github.com/snail007/proxy/services/http/http.go:309 +0xad
github.com/snail007/proxy/services.Run(0x1184c090, 0x4, 0x0, 0x0, 0x11876a80, 0x
0, 0x0)
        /Users/go/src/github.com/snail007/proxy/services/service.go:65 +0x222
github.com/snail007/proxy/core/runner.StartWithLog(0x1184c090, 0x4, 0x1184a840,
0x1c, 0x0, 0x0, 0x1c, 0x40471e, 0x1183a030)
        /Users/go/src/github.com/snail007/proxy/core/runner/runner.go:643 +0xb91
a
github.com/snail007/proxy/core/runner.Start(...)
        /Users/go/src/github.com/snail007/proxy/core/runner/runner.go:69
main.main()
        /Users/go/src/github.com/snail007/proxy/main.go:61 +0x75

## Steps to Reproduce

1.
1.
1.
1.

## Context (Environment)

1. proxy version is : v?
1. full command is :?
1. system is :
1. full log is: ?

**Comment by snail007** [comment]
https://github.com/syncthing/syncthing/issues/5575

**Comment by Schr0dingerCat** [comment]
英语渣去看了，怎么意思是，装了那个sdk，就不报错了吗？

**Comment by snail007** [comment]
装sdk或换系统

**Comment by Schr0dingerCat** [comment]
谢谢大大的热心回复
