### ISSUE TITLE
check update fail

### ISSUE THREAD

**Issue by snail007** [snail007/goproxy#286]
https://github.com/snail007/goproxy/blob/master/README_ZH.md#%E6%BA%90%E4%BB%A3%E7%A0%81%E7%94%B3%E6%98%8E

https://github.com/snail007/goproxy/wiki/%E6%8F%90%E7%A4%BA%E8%AE%BF%E9%97%AE%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%EF%BC%9F

**Comment by snail007** [comment]
problem of ban : #285

**Comment by blueway** [comment]
`LIC_DNS=8.8.4.4:53 ./proxy http -p :9090`,可以解决　`The owner of this website (lic00.host900.com) has banned your IP address` 这个问题吗？

**Comment by snail007** [comment]
checker removed since v7.7
