### ISSUE TITLE
Socks 转 SS+HTTP(s) 之后，程序里面使用 https_proxy 有 SSLError Unexpected EOF 之类的问题

### ISSUE THREAD

**Issue by designinlife** [snail007/goproxy#287]
GoProxy version: 7.6 (之前的版本也是如此)
命令: ./proxy sps -S socks -T tcp -P 127.0.0.1:1080 -t tcp -p :1081 -h aes-256-cfb -j 123456

Python 中使用 requests 库发送请求会出现异常警告：
(Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

**Comment by snail007** [comment]
测试请用curl，其它不负责。
