### ISSUE TITLE
is http --bind-listen deprecated in 7.7?

### ISSUE THREAD

**Issue by awatuna** [snail007/goproxy#289]
## Expected Behavior
in 7.6 it works, outbound connections use ipv4 ip, otherwise it defaults to ipv6 ip on dual stack machines

## Current Behavior
in 7.7 it fails with
err : unknown long flag '--bind-listen'

## Steps to Reproduce

1. run this command line 
proxy http --local=0.0.0.0:8080 --bind-listen --local-type=tcp

## Context (Environment)

1. proxy version is : v7.7
1. full command is : proxy http --local=0.0.0.0:8080 --bind-listen --local-type=tcp
1. system is : centos 7 with latest updates and reboot
1. full log is: err : unknown long flag '--bind-listen'

**Comment by snail007** [comment]
https://snail007.github.io/goproxy/free_vs_commercial/
