### ISSUE TITLE
ws代理没有发出path啊

### ISSUE THREAD

**Issue by kxmp** [snail007/goproxy#298]
proxy socks -t ws -p 127.0.0.1:xxxx --local-ws-method=xxxx --local-ws-password=xxxx
proxy socks -T ws -P abc.de/path --parent-ws-method=xxxx --parent-ws-password=xxxx
带路径的是我用web服务器把他挂载了.
这个复现应该很简单 直接指向个web服务器然后看看get里面有没有路径就知道了.

本地测试了下发现能用的.  (不带路径可以用 带了路径不能用)
带了路径的用了之后流量显示发出了ws请求 但是请求的是 "/"
connect to parent fail, connect fail,unexpected HTTP response status: 200 
因为没发出路径所以直接拉了个网页回来 就报错200了.

客户端软件里还显示的
use ws parent [abc.de/xxxx] 反正就是带路径的!! 软件还识别出来了就是没发出去.

**Comment by kxmp** [comment]
另外我还发现日志有问题. 
我根本没接上代理 然后又自动跳本地直连了. 但是日志还显示的
use parent true : xxxxx
后面ip还就是我连接的那个网站的. 这根本不可能啊 所以这个应该是显示错误的.
然后我加了--always 又连不上了 日志里面全都是连接parent失败的

**Comment by snail007** [comment]
https://snail007.github.io/goproxy/page/free_vs_commercial/

**Comment by kxmp** [comment]
原来是这样啊!!
