### ISSUE TITLE
普通二级HTTP代理仍然需要 cert file 和 key file？

### ISSUE THREAD

**Issue by mengmo** [snail007/goproxy#3]
```
proxy http -t tcp -p "0.0.0.0:8090" -T tcp -P "127.0.0.1:1080"
2017/10/04 15:10:50 err : open proxy.crt: The system cannot find the file specified.
```
我以为按照教程中的示例来看，是不需要`cert file`和`key file`的
> 1.2.普通二级HTTP代理
> 使用本地端口8090,假设上级HTTP代理是22.22.22.22:8080
> ./proxy http -t tcp -p "0.0.0.0:8090" -T tcp -P "22.22.22.22:8080"
> 1.3.HTTP二级代理(加密)
> 二级HTTP代理(本地windows)
> ./proxy.exe http -t tcp -p ":8080" -T tls -P "22.22.22.22:38080" -C proxy.crt -K proxy.key
> 然后设置你的windos系统中，需要通过代理上网的程序的代理为http模式，地址为：127.0.0.1，端口为：8080,程序即可通过加密通道通过vps上网。

**Comment by snail007** [comment]
普通的代理底层就是普通tcp传输,是不需要设置cert file和key file的.
当底层使用tls时,cert file和key file的是为tls使用的.

**Comment by mengmo** [comment]
那么出错了是怎么回事？

**Comment by snail007** [comment]
那就是哪里没配置对,请贴出来你的操作步骤,参数,启动输出,然后才能进一步排查,或者进群交流更方便.
