### ISSUE TITLE
配置文件启动报错

### ISSUE THREAD

**Issue by helllkz** [snail007/goproxy#301]
root@ubuntu:/etc/proxy# proxy --version
free_8.0
root@ubuntu:/etc/proxy# /usr/bin/proxy @/etc/proxy/conf.txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9fc535]

goroutine 1 [running]:
main.main()
        proxy/main.go:78 +0x145

http
-t tls
-p :58000
-C /etc/proxy/proxy.crt
-K /etc/proxy/proxy.key
--log /tmp/proxy.log
--forever

**Comment by snail007** [comment]
是不是下载的最新版？8.0发布后更新过。

**Comment by helllkz** [comment]
是最新的，内容上部分的日志，下部分是配置文件内容

**Comment by snail007** [comment]
不用配置文件有没有问题？

**Comment by snail007** [comment]
重新下载试试,已经更新。

**Comment by helllkz** [comment]
> 不用配置文件有没有问题？

不用配置文件没问题
重新下载了安装文件，手动覆盖后，再把其他文件都放etc/proxy下面后就好了，之前是用那个自动安装脚本。
