### ISSUE TITLE
Proxy CPU占用100%

### ISSUE THREAD

**Issue by joewongex** [snail007/goproxy#310]
采用SOCKS二级代理(加密)，一级代理是CentOS 7.6.1810，一核一G，二级代理是Windows 7。Win7上Chrome设置二级代理的地址通过代理上网，打开百度，一级代理的Proxy CPU占用率直接升到100%（平常都是不超过2%的）
Proxy版本：v8.0
一级代理执行命令：./proxy socks -t tls -p :3333 -C proxy.crt -K proxy.key --forever --log proxy.log --daemon
二级代理执行命令：proxy.exe socks -p ":3334" -t tcp -T tls -P "ip:3333" -C proxy.crt -K proxy.key --debug

Chrome浏览器通过在快捷方式，目标中加入“ --proxy-server="socks5://127.0.0.1:3334"选项使用代理上网。

**Comment by snail007** [comment]
没有日志无法定位问题。

**Comment by joewongex** [comment]
> 没有日志无法定位问题。

日志全都是
xxx connected
xxx released
这样的

**Comment by snail007** [comment]
内容不具体无法分析。

**Comment by snail007** [comment]
请按照issue模板完整描述一下。

**Comment by joewongex** [comment]
我觉得我写得够清楚了，算了，换个软件，没那么多时间给你排错。

**Comment by snail007** [comment]
fixed in v8.9
