### ISSUE TITLE
看到goproxy 有docker版本了，docker,这个http->ss，应该怎么写？

### ISSUE THREAD

**Issue by aff2018** [snail007/goproxy#311]
假设已经存在一个普通的HTTP（S）代理：127.0.0.1：8080，现在我们把它转为同时支持HTTP（S）和SOCKS5和SS的普通代理，转换后的本地端口为18080，SS加密方式： AES-192-CFB，SS密码：pass。
命令如下：
./proxy sps -S http -T tcp -P 127.0.0.1:8080 -t tcp -p :18080 -h aes-192-cfb -j pass

请教docker的这句应该怎么写？

**Comment by snail007** [comment]
一样的

**Comment by aff2018** [comment]
帮忙看一下是这样吗？

docker run -d --restart=always --name goproxy -e sps -S http -T tcp -P
127.0.0.1:8888 -t tcp -p 18888:18888 -h chacha20-ietf -j music
snail007/goproxy:latest

snail007 <notifications@github.com>于2019年8月17日 周六10:37写道：

**Comment by aff2018** [comment]
好象不对，很多参数，不知道如何弄，求大佬给写一下。

bwh 123 <aff201805@gmail.com>于2019年8月17日 周六12:25写道：
