### ISSUE TITLE
Load balancing is missing in socks mode

### ISSUE THREAD

**Issue by PtDragon** [snail007/goproxy#313]
Trying to use load balancing just throws out error.
## Expected Behavior

working as in http mode for load balancing options
## Current Behavior

error appears
## Steps to Reproduce

1. ./proxy socks --lb-method=leastconn -p "0.0.0.0:3080" -T tcp -P "127.0.0.1:1080" -P "127.0.0.1:1081" -P "127.0.0.1:1082" -P "127.0.0.1:1083" -P "127.0.0.1:1084" -P "127.0.0.1:1085" -P "127.0.0.1:1086" -P "127.0.0.1:1087" --daemon
2019/08/27 17:07:32 err : unknown long flag '--lb-method'

## Context (Environment)

1. proxy version is : v8.1(latest at the moment)
1. full command is : ./proxy socks --lb-method=leastconn -p "0.0.0.0:3080" -T tcp -P "127.0.0.1:1080" -P "127.0.0.1:1081" -P "127.0.0.1:1082" -P "127.0.0.1:1083" -P "127.0.0.1:1084" -P "127.0.0.1:1085" -P "127.0.0.1:1086" -P "127.0.0.1:1087" --daemon
2019/08/27 17:07:32 err : unknown long flag '--lb-method'
1. system is : Linux

I'm trying to use it for proper load balancing of socks5 servers(v2ray client side is working as socks5) with full support of UDP commands as i need them. 
Else i could use any TCP load balancer. 
I hope this can be solved easily enough on your side (as i think there is just a bit of code missing).

**Comment by snail007** [comment]
--lb-method  only for commercial edition

**Comment by PtDragon** [comment]
So if i buy commercial edition it should do load balancing well?
Because for now on free edition it does not balance, just uses first server it finds(and also eats tons of CPU compared to gobetween).
If commercial edition is necessary could you help me to buy it(i don't know where to pay for it and could not even read differences between editions as i do not know Chinese)?

**Comment by snail007** [comment]
details here : https://snail007.github.io/goproxy/page/free_vs_commercial_en/

**Comment by PtDragon** [comment]
Thanks! I see now why it does not balance.
The only thing i don't understand yet is how to pay for it (on authorization website there is no button to buy). 
Should i mail you directly to choose a payment method? 
I do not have any cryptocurrencies, but i have a visa card.

**Comment by snail007** [comment]
don't  hurry, let us resolve the CPU  issue firstly, for convenience  you can add my telegram : arraykeys .

**Comment by PtDragon** [comment]
Sadly i cannot use Telegram(used it only to download kernel for my phone but got banned suddenly). 
But i have a gmail too and if it can be convenient we can use hangouts chat or mails.

**Comment by snail007** [comment]
my hangouts account is arraykeys@gmail.com , we can use hangouts chat.

**Comment by PtDragon** [comment]
I tried to contact you on Hangouts but didn't receive an answer.
Where can i see price?
Is it possible to buy with Visa or Masercard?

**Comment by snail007** [comment]
email to me please, arraykeys@gmail.com, i didn't received any chat  request in Google hangouts, maybe something wrong?

**Comment by PtDragon** [comment]
email sent
