### ISSUE TITLE
非常不错的工具，建议内网穿透也增加socks代理模式，一个一个地端口映射比较麻烦

### ISSUE THREAD

**Issue by victor-infosec** [snail007/goproxy#319]
建议增加反向socks代理和多级反向socks代理的功能

**Comment by snail007** [comment]
内网穿透加穿透socks代理即可

**Comment by victor-infosec** [comment]
好的，就是得执行两条命令了 ^_^

**Comment by richard1225** [comment]
> 内网穿透加穿透socks代理即可

请问内网机器还是执行 client 吗?
server 机器是执行bridge 和 server? 

请问要怎么执行呢? 内网穿透+socks5代理还是很常用的

**Comment by snail007** [comment]
后面我出个视频教程
