### ISSUE TITLE
tserver 提示没有 -r 命令

### ISSUE THREAD

**Issue by 0x92bf** [snail007/goproxy#320]
运行：./proxy server -r ":28080@:80" -P "127.0.0.1:33080" -C proxy.crt -K proxy.key
提示：
proxy: error: unknown short flag '-r', try --help

**Comment by snail007** [comment]
你是很旧的版本吧，最新版有这个。

**Comment by 0x92bf** [comment]
> 你是很旧的版本吧，最新版有这个。

用的master分支编译的

**Comment by snail007** [comment]
那是3.x版本，现在都v8.3了！
