### ISSUE TITLE
公网vps+内网机器(可访问公网和内网服务，无公网ip)，如何配置可使任意外网机器访问内网服务？

### ISSUE THREAD

**Issue by oaspireo** [snail007/goproxy#322]
## Expected Behavior
通过配置vps和内网机器，任意外网机器可以访问内网web服务
## Current Behavior
内网机器浏览器访问`vps ip:8080`可以看到相关web，外网机器访问无效

## Context (Environment)
1. proxy version is : v8.3
2. full command is :
##### vps
- ./proxy tbridge -p ":28080" -C proxy.crt -K proxy.key --daemon
- ./proxy tserver -r ":8080@:18080" -P "127.0.0.1:28080" -C proxy.crt -K proxy.key --daemon

##### 内网机器
- ./proxy tclient -P "vps的ip:28080" -C proxy.crt -K proxy.key --daemon
- ./proxy tcp -p ":18080" -T tcp -P "内网web服务地址:8888" --daemon

3. system is : vps:centos7，内网机器:macos 10.14.6，外网机器:任意

**Comment by snail007** [comment]
目前看来，架构和命令都没问题，不过tcp代理可以去掉，server的-r支持访问其他内网机器。内网机器可以访问说明bridge的8080是穿透成功的，另外无法访问有可能是你的网络到vps的8080不通或者阻断，防火墙都有可能。

**Comment by oaspireo** [comment]
> 目前看来，架构和命令都没问题，不过tcp代理可以去掉，server的-r支持访问其他内网机器。内网机器可以访问说明bridge的8080是穿透成功的，另外无法访问有可能是你的网络到vps的8080不通或者阻断，防火墙都有可能。

谢谢，-r参数简化了我的命令行数量，原本是写了多个bridge、sever和client的。我是有多个web服务需要穿透，其中一个很简单的ftp可以正常访问，其它的就不成。一开始怀疑是报文头的事，配上--http-host还是不成，估计是服务器防火墙的问题。
