### ISSUE TITLE
linux运行时报错

### ISSUE THREAD

**Issue by luhang222** [snail007/goproxy#324]
使用的socks5代理
proxy socks -t tcp -p ":8999"

socks conn handler crashed with err : interface conversion: interface {} is nil, not uint 
stack: goroutine 721 [running]:
runtime/debug.Stack(0xc000466500, 0xac0920, 0xc0003f82a0)
        /usr/local/go1.11/src/runtime/debug/stack.go:24 +0xa7
github.com/snail007/proxy/services/socks.(*Socks).socksConnCallback.func1(0xc0002e4000, 0xc000438470)
        proxy/services/socks/socks.go:517 +0x5a
panic(0xac0920, 0xc0003f82a0)
        /usr/local/go1.11/src/runtime/panic.go:513 +0x1b9
github.com/snail007/proxy/services/socks.(*Socks).proxyTCP(0xc0002e4000, 0xc000438470, 0xc000448c60)
        proxy/services/socks/socks.go:616 +0x2c9f
github.com/snail007/proxy/services/socks.(*Socks).socksConnCallback(0xc0002e4000, 0xc644a0, 0xc0003ec060)
        proxy/services/socks/socks.go:573 +0x369
github.com/snail007/proxy/services/socks.(*Socks).socksConnCallback-fm(0xc644a0, 0xc0003ec060)
        proxy/services/socks/socks.go:489 +0x3e
github.com/snail007/proxy/core/cs/server.(*ServerChannel).ListenTCP.func1.2(0xc00001ccc0, 0xc000304170, 0xc0002adaa0)
        proxy/core/cs/server/server.go:239 +0x90
created by github.com/snail007/proxy/core/cs/server.(*ServerChannel).ListenTCP.func1
        proxy/core/cs/server/server.go:218 +0x7e

**Comment by snail007** [comment]
多谢反馈，已经解决，从重新下载最新版即可。
