### ISSUE TITLE
有计划提供ss server吗？

### ISSUE THREAD

**Issue by cole-dda** [snail007/goproxy#326]
现在支持http，socks等，有计划支持ss server吗？如：
proxy ss -T ssh host1:port1    -t tcp host2:port2 -h xxx -j pass

**Comment by snail007** [comment]
看手册！SPS！

**Comment by cole-dda** [comment]
sps好像不支持 -T ssh，仅仅支持 -S http，-S socks 等。如果使用sps，需要使用2个命令，先启动一个socks，再启动一个 sps 通过个前面的socks。

**Comment by snail007** [comment]
看手册！独立服务！！
