### ISSUE TITLE
缺少-F auth-file 指定认证文件的选项

### ISSUE THREAD

**Issue by viphxin** [snail007/goproxy#329]
请问指定auth-file 文件怎么指定呢？
usage: proxy socks [<flags>]

proxy on ssh mode

Flags:
      --help                     Show context-sensitive help (also try --help-long and --help-man).
      --version                  Show application version.
      --debug                    debug log output
      --daemon                   run proxy in background
      --forever                  run proxy in forever,fail and retry
      --log=""                   log file path
      --debug-dir=""             ./
      --nolog                    turn off logging
  -P, --parent= ...              parent address, such as: "23.32.32.19:2800?w=1" ; For ws/wss : "23.32.32.19:28008/test?w=1&m=WS_METHOD&k=WS_PASSWORD/", '/test' is websocket's url path, w is weight, m is parent's ws
                                 encrypt method, k is parent's ws encrypt password
  -T, --parent-type=tcp          parent protocol type <tls|tcp|kcp|ssh|ws|wss>
  -t, --local-type=tcp           local protocol type <tls|tcp|kcp|ws|wss>
  -p, --local=":33080"           local ip:port to listen
  -C, --cert="proxy.crt"         cert file for tls
      --ca=""                    ca cert file for tls
  -K, --key="proxy.key"          key file for tls
  -u, --ssh-user=""              user for ssh
  -S, --ssh-key=""               private key file for ssh
  -s, --ssh-keysalt=""           salt of ssh private key
  -D, --ssh-password=""          password for ssh
      --always                   always use parent proxy
      --timeout=5000             tcp timeout milliseconds when connect to real server or parent proxy
      --interval=10              check domain if blocked every interval seconds
  -b, --blocked=""               blocked domain file , one domain each line
  -d, --direct=""                direct domain file , one domain each line
  -g, --local-bind-ips=LOCAL-BIND-IPS ...  
                                 if your host behind a nat,set your public ip here avoid dead loop
  -q, --dns-address=""           if set this, proxy will use this dns for resolve doamin
  -e, --dns-ttl=300              caching seconds of dns query result
  -z, --local-key=""             the password for auto encrypt/decrypt local connection data
  -Z, --parent-key=""            the password for auto encrypt/decrypt parent connection data
  -m, --local-compress           auto compress/decompress data on local connection
  -M, --parent-compress          auto compress/decompress data on parent connection
      --intelligent=intelligent  settting intelligent HTTP, SOCKS5 proxy mode, can be <intelligent|direct|parent>
      --parent-tls-single        conntect to parent insecure skip verify
      --local-tls-single         it's used when local type is tls
      --parent-ws-method="aes-192-cfb"  
                                 method of parent ws's encrpyt/decrypt, these below are supported :
                                 aes-192-cfb,aes-192-ctr,des-cfb,bf-cfb,chacha20,aes-128-cfb,aes-128-ctr,aes-256-ctr,cast5-cfb,rc4-md5,rc4-md5-6,chacha20-ietf,aes-256-cfb
      --parent-ws-password="snail007/goproxy"  
                                 password of parent ws's encrpyt/decrypt
      --local-ws-method="aes-192-cfb"  
                                 method of local ws's encrpyt/decrypt, these below are supported :
                                 cast5-cfb,rc4-md5,rc4-md5-6,chacha20-ietf,aes-256-cfb,aes-128-ctr,aes-256-ctr,des-cfb,bf-cfb,chacha20,aes-128-cfb,aes-192-cfb,aes-192-ctr
      --local-ws-password="snail007/goproxy"  
                                 password of parent ws's encrpyt/decrypt
      --kcp-key="secrect"        pre-shared secret between client and server
      --kcp-method=aes           encrypt/decrypt method, can be: aes, aes-128, aes-192, salsa20, blowfish, twofish, cast5, 3des, tea, xtea, xor, sm4, none
      --kcp-mode=fast            profiles: fast3, fast2, fast, normal, manual
      --kcp-mtu=450              set maximum transmission unit for UDP packets
      --kcp-sndwnd=1024          set send window size(num of packets)
      --kcp-rcvwnd=1024          set receive window size(num of packets)
      --kcp-ds=10                set reed-solomon erasure coding - datashard
      --kcp-ps=3                 set reed-solomon erasure coding - parityshard
      --kcp-dscp=0               set DSCP(6bit)
      --kcp-nocomp               disable compression
      --kcp-acknodelay           be carefull! flush ack immediately when a packet is received
      --kcp-nodelay=0            be carefull!
      --kcp-interval=50          be carefull!
      --kcp-resend=0             be carefull!
      --kcp-nc=0                 be carefull! no congestion
      --kcp-sockbuf=4194304      be carefull!
      --kcp-keepalive=10         be carefull!

没有-F -a 这些参数

**Comment by viphxin** [comment]
我下载的是刚刚作者发布的release8.5的版本

**Comment by snail007** [comment]
请参考：https://snail007.github.io/goproxy/page/free_vs_commercial/

**Comment by viphxin** [comment]
👌 感谢作者
