### ISSUE TITLE
内网穿透 client链接报错，换了 tcp /ws 协议报错一样

### ISSUE THREAD

**Issue by a001189** [snail007/goproxy#333]
proxy client -P *:3672 -T tcp --k 801
proxy client -P 1.1.1.1:3672 -T ws --ws-password 123qaz --k 801
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
2019/11/14 19:15:37 [ERR] yamux: Invalid protocol version: 1
2019/11/14 19:15:37 accept stream err: invalid protocol version, retrying...
^C2019/11/14 19:15:39 Received an interrupt, stopping services...
2019/11/14 19:15:39 service client stopped

**Comment by snail007** [comment]
版本不一致导致的

**Comment by a001189** [comment]
可以了，感谢
