### ISSUE TITLE
网易云音乐UWP应用  代理请求失败

### ISSUE THREAD

**Issue by zhyy2008z** [snail007/goproxy#336]
## Steps to Reproduce

1. 创建一个普通HTTP一级代理
1. 设置系统代理服务器为该一级代理
1. 将所有UWP应用设置为Loopback 例外（允许uwp应用使用刚刚建立的代理服务器）
1. 随意点击几首歌曲，除第一首可以正常打开外，剩余歌曲均无法加载（提示：歌曲播放失败，请确保网络连接及播放设备正常）

## Context (Environment)

1. proxy version is : v8.7
1. full command is :  proxy.exe http -t tcp -p "127.0.0.1:18308"
1. system is : win10 1909
1. full log is: 
2019/11/26 23:01:07 conn 127.0.0.1:6106 - 59.111.181.35:80 connected [music.163.com:80]
2019/11/26 23:01:07 conn 127.0.0.1:6109 - 59.111.181.35:80 connected [music.163.com:80]
2019/11/26 23:01:07 GET:http://m7.music.126.net/20191126232605/5ea36d667a64b4420879ef6f57966c59/ymusic/f43f/f941/1b5f/a069081483aeef97727ba139b91cf671.mp3
2019/11/26 23:01:07 use parent : false, m7.music.126.net:80
2019/11/26 23:01:07 conn 127.0.0.1:6111 - 111.6.227.226:80 connected [m7.music.126.net:80]
2019/11/26 23:01:07 conn 127.0.0.1:6111 - 111.6.227.226:80 released [m7.music.126.net:80]
2019/11/26 23:01:10 GET:http://m8.music.126.net/20191126232608/cbf6e47af8401e39db5c5b0138da5e3e/ymusic/f46b/4c78/30a0/2d81ed2c71aff805be226f7f5d85b041.mp3
2019/11/26 23:01:10 use parent : false, m8.music.126.net:80
2019/11/26 23:01:10 conn 127.0.0.1:6113 - 117.161.66.185:80 connected [m8.music.126.net:80]
2019/11/26 23:01:11 conn 127.0.0.1:6113 - 117.161.66.185:80 released [m8.music.126.net:80]
2019/11/26 23:01:12 conn 127.0.0.1:6047 - 202.89.233.101:443 released [cn.bing.com:443]
2019/11/26 23:01:15 conn 127.0.0.1:6106 - 59.111.181.35:80 released [music.163.com:80]
2019/11/26 23:01:16 conn 127.0.0.1:6109 - 59.111.181.35:80 released [music.163.com:80]

## Detailed Description

不止网易云音乐有此问题，搜狐视频 uwp 应用所有网络请求都会失败，提示：网络连接失败，请检查网络连接是否有效。

测试其他软件创建的代理服务器无此问题，例如：阿呆喵。

另外，我测试了goproxy作为二级代理的情况，强制goproxy使用其他代理服务器作为上级代理，发现**无此问题**。

那么，我猜测此问题可能仅出现在goproxy设置为无上级代理的情况。

**Comment by snail007** [comment]
感谢反馈，已经修复，我看看是下个版本v8.9或者更新v8.7版本的发布。

**Comment by snail007** [comment]
已经更新v8.7，重新下载试试吧。

**Comment by zhyy2008z** [comment]
测试已经正常，很完美，非常感谢！
