### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by 1542254356** [snail007/goproxy#338]

**Comment by snail007** [comment]
可以，内网穿透即可，172启动bridge和server，192启动client与s5

**Comment by snail007** [comment]
可以,配合内网穿透即可，172启动bridge和s5,192启动server把172的s5 A 映射到本地，然后本地原有s5 B设置上级为A即可。

**Comment by 1542254356** [comment]
172   
./proxy socks -t tcp -p "0.0.0.0:6665" -T tcp -P "127.0.0.1:6666"
./proxy bridge -p ":6666" -C proxy.crt -K proxy.key
192
./proxy socks -t tcp -p "0.0.0.0:6666"
./proxy client -P "172.1.1.233:6666" -C proxy.crt -K proxy.key

然后我再连172的s5代理吗
