### ISSUE TITLE
代理本地路由器管理页面失败

### ISSUE THREAD

**Issue by zhyy2008z** [snail007/goproxy#339]
## Steps to Reproduce

1. 创建一个普通HTTP一级代理
1. 设置系统代理服务器为该一级代理
1. 访问由家中路由器创建的路由器登陆界面，如：http://192.168.3.1/

## Context (Environment)

1. proxy version is : v8.7
1. full command is :  proxy.exe http -t tcp -p "127.0.0.1:18308"
1. system is : win10 1909
1. full log is: 
2019/12/02 21:01:41 GET:http://192.168.3.1/
2019/12/02 21:01:41 use parent : false, 192.168.3.1:80
2019/12/02 21:01:41 conn 127.0.0.1:2618 - 192.168.3.1:80 connected [192.168.3.1:80]

## Detailed Description

被测试路由器品牌型号为荣耀路由pro2，路由器前端框架应该是vuejs。

另外，使用goproxy代理访问了局域网中由另一台电脑的iis服务器创建的网站（iis10的默认初始页面,纯html静态页面），**无此问题**。

测试由其他软件创建的代理服务器**无此问题**，例如：阿呆喵。

我测试了goproxy作为二级代理的情况，强制goproxy使用其他代理服务器作为上级代理，发现**无此问题**。

结论：
1、此问题可能仅出现在goproxy设置为无上级代理的情况。
2、无法确定是否与被访问web服务器或者被访问者是网关有关？
3、goproxy的安全策略？

**Comment by snail007** [comment]
8.7更新过，先确认是不是最新更新的。

**Comment by zhyy2008z** [comment]
已重新下载并测试（proxy.exe SHA256: 897CB925B7CBDD34EF5721305BD9F45EDA819EE763792D05846A325E76E9D20B
），依然如此。之前网易云音乐问题也是我汇报的，这个与那个问题应该不是同一个问题。

**Comment by snail007** [comment]
我用同样的方式代理，访问openwrt路由器管理页面没有发现问题。我没有你那款路由器，我这边没法复现，暂时无法定位原因。

**Comment by zhyy2008z** [comment]
抱歉，重启操作系统后恢复正常，可能与我的操作系统运行异常有关。

**Comment by zhyy2008z** [comment]
刚才搞错了，是我昨晚睡前把192.168.3.1放到黑名单里（会通过二级代理访问路由器页面）了，可以暂时绕过这个问题，导致可以正常代理。

移除这个配置并重启proxy.exe后，还是不能正常访问。测试了另一台电脑也是如此。

另外，我测试了公司的路由器（BL-Link）登录页，这个可以正常访问。

以后再遇到可以在公网访问的页面并且proxy.exe无法代理时我再跟您汇报，以便于您定位问题！

**Comment by snail007** [comment]
你的需求是强制走上级，你需要加上--always参数。默认智能判断是否走上级。

**Comment by zhyy2008z** [comment]
我没有用--always参数，我把192.168.3.1放在黑名单里（走上级），这样就可以正常访问192.168.3.1了。

**Comment by zhyy2008z** [comment]
已找到如这个问题类似的可以公网访问的网页：http://114.116.81.183:10002/，该网站使用blazor技术搭建，通过goproxy代理会出错：报告某些dll请求失败，空回应。

**Comment by snail007** [comment]
我同单独一级模式和二级模式用最新版测试均正常.该网站一次性下载东西过多,需要关闭并发数量: `--max-conns-rate 0`,不然会超过默认20,有的连接就被关闭.

**Comment by zhyy2008z** [comment]
您好，设置过并发数量后，对  http://114.116.81.183:10002/ 的访问确实已经正常。 但是，之前反馈的荣耀路由pro2登录页问题仍然存在，我以后再发现公网可访问的有问题的页面再跟您汇报。
