### ISSUE TITLE
cpu 用了一段时间后，变得很高

### ISSUE THREAD

**Issue by starjiang** [snail007/goproxy#341]
最新的linux amd64 8.7 版本，cpu 用了一段时间后，变得很高

**Comment by snail007** [comment]
请按照issue模板提供完整信息，你这样无法排查。

**Comment by f4nff** [comment]
性能垃圾，200Mbps的带宽，http带宽 cpu 飙升到20%  ，正常其他go项目是3%

**Comment by snail007** [comment]
fixed in v8.9
