### ISSUE TITLE
请求头里没有path的问题

### ISSUE THREAD

**Issue by lixiaomeng8520** [snail007/goproxy#343]
一些客户端，比如java的URL请求或者早期的curl请求时，header里不会自动在最后加上斜杠，比如
`curl http://www.baidu.com`，打印出的header为
`GET http://www.baidu.com HTTP/1.1`，
这时如果通过goproxy代理，则请求头会变为
`GET  HTTP/1.1`，
path信息为空，服务端会返回 400。

解决办法有2个，
1. 在客户端自动添加斜杠。
2. 代理处自动添加斜杠（nginx代理时，会自动加上）。

希望作者能处理第二种。

**Comment by snail007** [comment]
多谢反馈，v8.8已经做了兼容处理，这种情况会自动加上/

**Comment by lixiaomeng8520** [comment]
@snail007 OK
