### ISSUE TITLE
网络验证失败

### ISSUE THREAD

**Issue by xyz0101** [snail007/goproxy#347]
## Steps to Reproduce

本机可以上网，但是一直说网络验证失败，有木有遇到过类似情况的啊

## Context (Environment)

1. proxy version is : v?
1. full command is :?
1. system is :
1. full log is: ?

## Detailed Description

![image](https://user-images.githubusercontent.com/20569072/71976903-716e9100-3252-11ea-8b22-cb69fa26d629.png)

**Comment by snail007** [comment]
这是商业版
