### ISSUE TITLE
Extreme CPU load under some conditions

### ISSUE THREAD

**Issue by PtDragon** [snail007/goproxy#348]
Right now goproxy eats over 3 full CPU cores(320-350%). 
Where the problem is: DNS resolving code.

## Expected Behavior
Working well without resolving when there is no need.
for example(ips are random in example) : 
client requests connection to 7.7.7.7:65332
server does it directly without doing any DNS requests.

## Current Behavior
Horribly big CPU load even if no traffic goes anymore thru goproxy after using torrent client on a popular torrent.
Why? Because it FLOODS my DNS server taking lot of resources to do it.

## Possible Solution
do not resolve IPs if not requested to resolve. 

## Steps to Reproduce
1. Configure qBitTorrent to use socks5 for everyting
2. Start any popular torrent with thousands of peers
3. Observe huge CPU load and flood to DNS server for a long time (for me it eaten over 1h of CPU time already).

## Context (Environment)

1. proxy version is : commercial_8.3
1. full command is : ./proxy socks  --lb-method=roundrobin -p 192.168.4.252:9990
1. system is : linux x86_64
1. full log is: not required as it can be miles long and issue is easy to reproduce.

**Comment by snail007** [comment]
thanks for your reporting, i will check it soon .

**Comment by PtDragon** [comment]
Hello!
Just wondering how is it going because it limits usage in my case for apps that require some thousands of connections?

**Comment by snail007** [comment]
because of virus  2019-nCoV, checking is delayed.

**Comment by PtDragon** [comment]
Thanks for answer!
Completely understandable reason, will wait as much as needed!
Hope that virus will be disappearing  completely soon causing as few problems as possible!

**Comment by snail007** [comment]
fixed in v8.9

**Comment by PtDragon** [comment]
Yeah, load did decrease a lot!
But after updating i have another problem:
checking fail , your network seems having something wrong , please check your network and try again .
2020/03/13 23:50:01 retrying ... (1/3)

**Comment by PtDragon** [comment]
It was some network problem reaching your license servers.
So all is perfect, thanks!
