### ISSUE TITLE
Why changing README to Chinese?

### ISSUE THREAD

**Issue by dausruddin** [snail007/goproxy#354]
Hi. README was written in English but [was replaced completely with Chinese](https://github.com/snail007/goproxy/commit/44b359f300f2a397527f0d7d8c31b80c605b42ed). Why is that? I find it is hard to read when I need to use Google Translate.

Thanks

**Comment by snail007** [comment]
i have not changed anything, the project has two readme file , it's by guthub auto choosed to display based on your IP or browser's user agent.

**Comment by snail007** [comment]
thanks for your tip, i fixed it.

**Comment by dausruddin** [comment]
Thanks a lot :)
