### ISSUE TITLE
和python3 requests 库搭配使用存在报错问题

### ISSUE THREAD

**Issue by djerrystyle** [snail007/goproxy#355]
问题在requests下面提交了,不知道是goproxy的问题还是requests的问题,或者是写的代码存在问题; https://github.com/psf/requests/issues/5392

**Comment by djerrystyle** [comment]
原因是并发太高, 当我关闭了其他程序的并发请求, 一切都正常了

**Comment by snail007** [comment]
那看来应该是你系统默认的程序打开最大文件数没有调整，默认很低是1024。

**Comment by djerrystyle** [comment]
> 那看来应该是你系统默认的程序打开最大文件数没有调整，默认很低是1024。

我把程序针对单个host的并发从50调整成了20, 同时请求从500调整成了200,还是存在这个问题.
HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert unexpected message')],)",),))

句柄配置如下:
ulimit -n 65536
ulimit -u 2048
sysctl -w vm.max_map_count=262144
sudo sh -c "echo 'vm.max_map_count=262144' >> /etc/sysctl.conf"

设备性能64G内存,16核CPU,应该不存在问题,

之前用8.8版本, 一切正常, 但是输入 top,看到proxy会占用CPU 20%左右.

**Comment by djerrystyle** [comment]
我的项目中,用proxy做http代理, 监听3000端口, 然后用python写了一个循环监听, 当python使用代理监听到目标网站无法访问, 则判断本IP被封, 则用socat切换IP, 就是这样一个功能目的.

然后并发开启了20个proxy和20个监听脚本, 循环在四层做切换, 程序走的七层实现无感知的爬取操作.
