### ISSUE TITLE
P2P传输下，上传速度和下载速度的问题

### ISSUE THREAD

**Issue by joson1** [snail007/goproxy#365]
## 问题1
在P2P传输下，文件发送方的上传速度不能达到最大上车带宽  （实测最大上行带宽10MB/s，使用p2p传输只有5MB/s，在没有其它软件占用上行带宽的情况下）
## 问题2
文件发送方发送速度为5MB/s（左右）时，接收方的文件下载速度只有2MB/s（左右），但是在接收方使用流量监控软件监测goproxy的下载速度却是5MB/s（左右，大致与发送方上传速度一致）

## 总结
不知是否有方案可以提高上传速度，和解决上传速度和下载速度不一致的问题

### 给作者添麻烦了！

**Comment by snail007** [comment]
用的kcp协议，不可能慢速，额外发包占用一部分带宽
