### ISSUE TITLE
请教如何将一个带密码的代理转为本地代理

### ISSUE THREAD

**Issue by sinoXu** [snail007/goproxy#372]
我希望将一个带密码的代码转为本地不带密码的代理进行访问
比如像下面这样 
.\proxy.exe http -t tcp -p 127.0.0.1:3322 -T tcp -J 'https://user:pass@host:port' 
这样虽然能启动但是不起作用

**Comment by snail007** [comment]
请看手册 sps

**Comment by sinoXu** [comment]
现在可以了，非常感谢。
