### ISSUE TITLE
 --forever and --intelligent parameter work failure

### ISSUE THREAD

**Issue by wimmerX** [snail007/goproxy#374]
--forever and --intelligent parameter work failure
## Expected Behavior

1.The forever parameter should make the goproxy program automatically run after the system reboot.
2.The intelligent parameter should be able to automatically implement intelligent-agents according to block and direct,failed to implement the function described in the manual.
## Current Behavior

1.After the system restarts, the program does not run automatically.
2.When I use --intelligent=direct all requests did not go to the superior agent,example visiting www.google.com.  When I use --intelligent=intelligent,all requests  go to the superior agent,example visiting ip138.com.

## Context (Environment)

1. proxy version is : v9.5
1. full command is :`sudo proxy socks -t tls -p ":18080" -T tls -P "x.x.x.x:18080" -C proxy.crt -K proxy.key  --dns-address "8.8.8.8:53" --dns-ttl 300 --intelligent direct --forever --daemon --log proxy.log`

1. system is :centos 7.3
1. partial key logs:
2020/06/01 18:33:17 conn [::1]:54948 - play.google.com:443 released
2020/06/01 18:33:59 ip ::1 rate, current: 1/s, max: 20/s
2020/06/01 18:33:59 conn [::1]:55432 - www.youtube.com:443 connected
2020/06/01 18:33:59 conn [::1]:39792 - mtalk.google.com:443 released
2020/06/01 18:33:59 conn [::1]:54700 - www.google.com:443 released
2020/06/01 18:34:02 conn 127.0.0.1:45228 - push.services.mozilla.com:443 released
2020/06/01 18:34:19 clean process 7097
##################manual restart#################
2020/06/02 09:09:12 forever proxy [PID] 13863 running...
2020/06/02 09:09:12 worker proxy [PID] 13935 running...

**Comment by snail007** [comment]
you are  not understand the intelligent mode  incorrectly.

**Comment by wimmerX** [comment]
Using  `--intelligent=direct ` argument,to access this URL  `0rz.tw ` which belong to the blocked file ,GP should request the parent proxy, while access the URL excluded in the blocked or included in the direct file,It should access directly by the local proxy.isn't it like this?

**Comment by snail007** [comment]
> Using `--intelligent=direct ` argument,to access this URL `0rz.tw ` which belong to the blocked file ,GP should request the parent proxy, while access the URL excluded in the blocked or included in the direct file,It should access directly by the local proxy.isn't it like this?

correct

**Comment by wimmerX** [comment]
I found the reason. I originally thought that as long as the parameters `--intelligent=direct `were specified, the GP would use the own file in its install directory by default, but I was wrong. Manual and 
explicit specified parameters with  `-b`  using path of blocked file still needed. 
Thanks for your reply.
GP is powerful!

**Comment by wimmerX** [comment]
Will the --forever configuration parameters restart as the system restarts?

**Comment by snail007** [comment]
--forever is just a monitor of goproxy's subprocess, no more functions. you  understand wrong about it .

**Comment by wimmerX** [comment]
Aha,I get it.
