### ISSUE TITLE
Linux ip max conns rate reached , current: 20/s, max: 20/s, kill the connection ..

### ISSUE THREAD

**Issue by kamike** [snail007/goproxy#389]
proxy http -t tcp -p "0.0.0.0:45003" --debug
启动后，浏览器访问，会一直没相应，查看日志：
Linux ip max conns rate reached , current: 22/s, max: 20/s, kill the connection ..

设置最大数量后还是一的错误，就算设置1000还是访问不了

系统信息：
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost proxy]# proxy http -t tcp -p "0.0.0.0:45003" --debug  --max-conns-rate 50

proxy free version 10.0  by snail , email : arraykeys@gmail.com
2020/08/07 21:45:36.619189 runner.go:1009: [profiling] cpu profiling save to file : ./cpu.prof
2020/08/07 21:45:36.619286 runner.go:1010: [profiling] memory profiling save to file : ./memory.prof
2020/08/07 21:45:36.619300 runner.go:1011: [profiling] block profiling save to file : ./block.prof
2020/08/07 21:45:36.619312 runner.go:1012: [profiling] goroutine profiling save to file : ./goroutine.prof
2020/08/07 21:45:36.619324 runner.go:1013: [profiling] threadcreate profiling save to file : ./threadcreate.prof
2020/08/07 21:45:36.636291 http.go:567: tcp http(s) proxy on [::]:45003

2020/08/07 21:45:42.914326 structs.go:661: GET:http://183.220.1.118:45003/
2020/08/07 21:45:42.914422 http.go:660: use parent : false, 183.220.1.118:45003
2020/08/07 21:45:42.914466 http.go:698: ip 222.209.32.231 rate, current: 1/s, max: 50/s
2020/08/07 21:45:42.916107 http.go:951: conn 222.209.32.231:61442 - 183.220.1.118:45003 connected [183.220.1.118:45003]
2020/08/07 21:45:42.917103 structs.go:661: GET:http://183.220.1.118:45003/
2020/08/07 21:45:42.917234 http.go:660: use parent : false, 183.220.1.118:45003
2020/08/07 21:45:42.917308 http.go:698: ip 192.168.1.1 rate, current: 1/s, max: 50/s
2020/08/07 21:45:42.918266 http.go:951: conn 192.168.1.1:40840 - 183.220.1.118:45003 connected [183.220.1.118:45003]
2020/08/07 21:45:42.919109 structs.go:661: GET:http://183.220.1.118:45003/
2020/08/07 21:45:42.919200 http.go:660: use parent : false, 183.220.1.118:45003
2020/08/07 21:45:42.919312 http.go:698: ip 192.168.1.1 rate, current: 2/s, max: 50/s
2020/08/07 21:45:42.920601 http.go:951: conn 192.168.1.1:40842 - 183.220.1.118:45003 connected [183.220.1.118:45003]
2020/08/07 21:45:42.921578 structs.go:661: GET:http://183.220.1.118:45003/
2020/08/07 21:45:42.921639 http.go:660: use parent : false, 183.220.1.118:45003
2020/08/07 21:45:42.921668 http.go:698: ip 192.168.1.1 rate, current: 3/s, max: 50/s
2020/08/07 21:45:42.923005 http.go:951: conn 192.168.1.1:40844 - 183.220.1.118:45003 connected [183.220.1.118:45003]
2020/08/07 21:45:42.923796 structs.go:661: GET:http://183.220.1.118:45003/
2020/08/07 21:45:42.923908 http.go:660: use parent : false, 183.220.1.118:45003
2020/08/07 21:45:42.923945 http.go:698: ip 192.168.1.1 rate, current: 4/s, max: 50/s
2020/08/07 21:45:42.925127 http.go:951: conn 192.168.1.1:40846 - 183.220.1.118:45003 connected [183.220.1.118:45003]
2020/08/07 21:45:42.925832 structs.go:661: GET:http://183.220.1.118:45003/
2020/08/07 21:45:42.925966 http.go:660: use parent : false, 183.220.1.118:45003
2020/08/07 21:45:42.926015 http.go:698: ip 192.168.1.1 rate, current: 5/s, max: 50/s
2020/08/07 21:45:42.927431 http.go:951: conn 192.168.1.1:40848 - 183.220.1.118:45003 connected [183.220.1.118:45003]

**Comment by snail007** [comment]
这是代理，要在需要代理的软件里面设置。它不是web服务，不是给你直接访问的。
