### ISSUE TITLE
GoProxy does support multi Tenant ?

### ISSUE THREAD

**Issue by northerndeveloper** [snail007/goproxy#397]
Hello

I want to know if GoProxy supports multi tenant ? I can use it for multiple customers with multiple remote ports ?

Thank you for your helps.

Regards
Alper

**Comment by snail007** [comment]
goproxy supports multi tenant and multiple customers with multiple remote ports, to get more usage information please read the manual : https://snail007.github.io/goproxy/manual/ , keyword: tcp, auth

In addition, authcation is a commercial edition feature.
