### ISSUE TITLE
flag `--blocked` `--direct` not supported for subcommand sps

### ISSUE THREAD

**Issue by rocaltair** [snail007/goproxy#398]
```
/tmp/proxy --version
free_10.0
```

`block` and `direct` files are both supported for `http` `socks`

I wonder why they are not supported for `sps`?

it's a little inconvenient to use `--redir` mode on router.

**Comment by snail007** [comment]
because of sps forward all traffic to upstream, not direct access.

**Comment by rocaltair** [comment]
I see...

so we need run two process on router to use transparent proxy locally, one for redirect, and the other for real proxy to communicate with proxy server on VPS.

I guess theres's much cost to run two processes in golang for low end routers.

thirst for this feature.

at last, I should say, goproxy is the most powerful proxy tool I've seen.

**Comment by snail007** [comment]
it's actually two processes need more memory than one, but if possible, you can run a goproxy as upstream on other PC  forward  traffic to vps, only sps on router.

**Comment by rocaltair** [comment]
got it, thx~
