### ISSUE TITLE
负载均衡的上游服务-P最多支持多少个输入呀

### ISSUE THREAD

**Issue by crisismaple** [snail007/goproxy#399]
RT，如果用commandline 以LB HA模式运行proxy的话，用-P指定上游代理最多指定多少个呢，可以有文件配置的方式指定多个么

**Comment by crisismaple** [comment]
还有一个问题，如果使用fast模式上报流量的话，单个连接每次上报的流量是增量的还是全量的？就是每一次上报之后本地计数器清零还是上报的是到当前为止这个连接的流量呀？还有，上报的API能不能支持自定义header或者query param？

**Comment by snail007** [comment]
https://snail.gitee.io/proxy/manual/zh/#/

**Comment by crisismaple** [comment]
> https://snail.gitee.io/proxy/manual/zh/#/

我看了mannal，但是我的问题是：
1、负载均衡情况下多个-P参数是不是支持以文件形式载入多条上级，如果不支持的话在命令参数里有无个数上限（我们的场景会有数百上千个上游）；
2、fast模式上报流量的时候针对单个连接，如果T1时刻上报是1KB，T2时刻上报是3KB，是意味着[0,T1]时间内这个连接产生了1KB流量、[0,T2]内产生了3KB流量(累计），还是[0,T1]时间内产生了1KB流量、[T1,T2]时间内产生了2KB流量（增量）；

这些好像在文档里没有描述的特别清楚

**Comment by snail007** [comment]
https://snail.gitee.io/proxy/manual/zh/#/ >>>配置文件
流量没有累加
