### ISSUE TITLE
我在netgear r6220 路由器上刷了 openwrt 的系统，想在路由上装一个goproxy，但是无法完成安装

### ISSUE THREAD

**Issue by Alvin-bobo** [snail007/goproxy#404]
经过 openwrt 官网查询，netgear r6220 的 cpu 是 MediaTek MT7621ST ，package architecture 是 mipsel_24kc ，所以下载的goproxy是 proxy-linux-mipsle.tar.gz 这个包，脚本是 install.sh（在代码里更改了如下内容：使用 proxy-linux-mipsle.tar.gz 替换 proxy-linux-amd64.tar.gz），通过执行命令行 ash install.sh 来安装，但是安装过程出现以下问题：在输出 installing ... 之后，等待几秒钟，程序就运行结束了，查看脚本的代码后发现，echo -e ">>> installing ... \n" 到 echo  -e ">>> install done, thanks for using snail007/goproxy $version\n" 代码之间的命令运行出现问题，但是不会报出错误，由于本人不懂所以在此提出，希望能得到大佬的帮助。

**Comment by Alvin-bobo** [comment]
后来在自己的服务器上（centos7）进行尝试性的安装（下载这个包：proxy-linux-amd64.tar.gz），发现可以安装完成。具体依据 install.sh 文件的命令来执行：先 cd 进入包的下载目录，再解压： tar zxvf 包名，配置环境变量：cp -f proxy /usr/bin/（将解压得到的 proxy 复制到 usr/bin 下），提升权限：chmod +x /usr/bin/proxy ，创建文件夹并将 blocked 和 direct 复制到文件夹下（不知道意义何在）： mkdir /etc/proxy，cp blocked /etc/proxy，cp direct  /etc/proxy，接着： cd 刚刚创建的文件夹，执行 proxy keygen -C proxy ，到此安装完成。

**Comment by Alvin-bobo** [comment]
后经过逐个测试，发现 proxy-linux-mipsle-softfloat.tar.gz 包可以在 netgear r6220 的 openwrt 上运行

**Comment by Alvin-bobo** [comment]
> 后经过逐个测试，发现 proxy-linux-mipsle-softfloat.tar.gz 包可以在 netgear r6220 的 openwrt 上运行

好像是 mipsel 但是这边的包是 mipsle ： le 写反了

**Comment by snail007** [comment]
不是写反了，这是go定义的。
