### ISSUE TITLE
socks 加认证失败

### ISSUE THREAD

**Issue by Ygrittevictorlee** [snail007/goproxy#412]
PS C:\Users\lee\Desktop\proxy10-1-windows-amd64> .\proxy.exe socks -t tcp -p ":33388" -F auth.txt
2020/12/10 17:48:58 err : unknown short flag '-F'
PS C:\Users\lee\Desktop\proxy10-1-windows-amd64> .\proxy.exe socks -t tcp -p ":33389" -a "user1:passwd1"
2020/12/10 17:52:17 err : unknown short flag '-a'
PS C:\Users\lee\Desktop\proxy10-1-windows-amd64>

![image](https://user-images.githubusercontent.com/44962965/101755988-7dbd3700-3b10-11eb-8350-0b4d24aa9de3.png)

**Comment by yanchuang12** [comment]
免费版不支持吧

**Comment by snail007** [comment]
认证是商业版功能。
