### ISSUE TITLE
goproxy 免费版支持https 代理吗

### ISSUE THREAD

**Issue by yanchuang12** [snail007/goproxy#417]
goporxy 源码编译 根本没有 --local-tls-single  这个字段解析

有个疑问 goproxy 源码编译是否支持 https 代理

常见问题中描述
https://snail007.github.io/goproxy/page/faq/goproxy%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94/
https代理：客户端和代理服务器之间是tls加密传输数据。
http代理是使用最广泛的代理，大部分客户端都不支持https代理。

答：goproxy支持http代理，https代理，https双向认证代理。
至于提供什么类型的代理，是参数-t决定的：
http代理 ：-t tcp
https代理：-t tls --local-tls-single，服务端需要设置tls证书。
https双向认证代理：-t tls，服务端和客户端都需要设置一样的tls证书。

源码编译 是否只能采用 https双向认证代理：-t tls
如果可以的话， 麻烦问下 https 双向认证 如何使用

**Comment by snail007** [comment]
请看源代码说明
