### ISSUE TITLE
--traffic-url中如果url中附带的有参数如?token=xxx会造成和bytes混在一起,--auth-url则不会,两个处理方法?

### ISSUE THREAD

**Issue by Shandawei** [snail007/goproxy#421]
--traffic-url中如果url中附带的有参数如?token=xxx会造成和bytes混在一起,--auth-url则不会,两个处理方法?
## Expected Behavior

--traffic-url会像--auth-url一样自动处理后面附加的参数
## Current Behavior

--traffic-url中如果url中附带的有参数如?token=xxx会造成和bytes混在一起
## Possible Solution

和--auth-url一样进行处理
## Steps to Reproduce

1.--traffic-url中url中附带的有参数如?token=xxx

## Context (Environment)

1. proxy version is : v?
1. full command is :?
1. system is :
1. full log is: ?

**Comment by snail007** [comment]
在下个版本中已经修复。

**Comment by Shandawei** [comment]
@snail007 thanks.
