### ISSUE TITLE
阿里云服务器重启一下,机器授权码都会变一次.重启后,超过授权码更新次数,无法启动

### ISSUE THREAD

**Issue by Shandawei** [snail007/goproxy#428]
## Expected Behavior

每次重启机器不会变

## Current Behavior

每次重启服务器则变更一下,导致机器授权码失效,但是平台又限制每月次数限制
## Possible Solution

限制服务器ip,或者其他验证方式.
## Steps to Reproduce

1.
1.
1.
1.

## Context (Environment)

1. proxy version is : v?
1. full command is :?
1. system is :
1. full log is: ?

**Comment by Shandawei** [comment]
@snail007 请问怎么解啊?

**Comment by snail007** [comment]
这是你的服务器问题，你要找阿里售后。

**Comment by zxiaozhou** [comment]
@Shandawei 云服务器是虚拟服务器，很容易出现变更，所以针对这种授权不合适。个人认为

**Comment by kimoziiiii** [comment]
他的意思是你要购买超超超级VIP，学到精髓了，付费了还给你各种限制，就为了防止恶意使用。我能理解，但是感觉这种做法很懒
