### ISSUE TITLE
后台守护运行如何结束啊

### ISSUE THREAD

**Issue by helllkz** [snail007/goproxy#43]
我在配置文件里面写了
--local-type=tcp
--local=:58000
--daemon
--forever
现在没法结束了呢，proxy的pid一直在增加，没法kill了

**Comment by helllkz** [comment]
![image](https://user-images.githubusercontent.com/14025168/37194649-3750ecce-23aa-11e8-96f0-15ce56e50816.png)

**Comment by helllkz** [comment]
重启了下服务器，并且启用了log就没这个问题了

**Comment by snail007** [comment]
说明启动参数或者其它问题导致子进程异常，启动就退出，然后daemon进程就会一直重启子进程，一般建议加上log，可以看到为什么子进程异常退出。

**Comment by helllkz** [comment]
@snail007 
还是有问题呢，我用配置文件启动就会出现这个问题
http
--local-type=tls
--local=:58000
--cert=/etc/proxy/proxy.crt
--key=/etc/proxy/proxy.key
--daemon
--forever
--log=/tmp/proxy.log
但是我直接启动就不会呢
proxy http -t tls -p ":58000" -C /etc/proxy/proxy.crt -K /etc/proxy/proxy.key --forever --daemon --log /tmp/proxy.log

**Comment by snail007** [comment]
引用的命令行类库对配置文件解析不是很好,容易出错,所以建议先写shell脚本取代,后续会优化这块.

**Comment by daoiqi** [comment]
```
--daemon
好像得放到外面执行，例如

./proxy @socks5_conf.txt --daemon
```

这样我是起来成功了， deamon放到配置文件里会失败
