### ISSUE TITLE
内网穿透 i/o timeout

### ISSUE THREAD

**Issue by Vastzhang97** [snail007/goproxy#440]
- 在开发机上能访问10.0.250.59:3306的数据库，希望通过开发机转发这个接口，让家里的电脑可以使用这个数据库
- 桥接机是有公网ip的树莓派4b 使用的软件是 proxy-linux-arm64-v8.tar.gz
- 开发机是没公网ip的windows 使用的软件是 proxy-windows-386.tar.gz
- 10.0.250.59是没公网ip的Ubuntu
- 已生成秘钥文件

操作步骤
1. 在桥接机（有公网ip的树莓派）执行  
`proxy tbridge -p ":13306" -C proxy.crt -K proxy.key`
`proxy tserver -r ":23306@10.0.250.59:3306" -P "127.0.0.1:13306" -C proxy.crt -K proxy.key`
2. 在开发机执行
`.\proxy.exe tclient -P "桥接机的公网ip:23306" -C .\key\proxy.crt -K .\key\proxy.key`
开发机日志
`2021/07/11 18:36:24 use tls parent pi.vastzhang.cn:23306
2021/07/11 18:36:24 client started
2021/07/11 18:36:24 session worker[1] started
2021/07/11 18:36:24 session worker[2] started
2021/07/11 18:36:24 session worker[3] started
2021/07/11 18:36:24 session worker[4] started
2021/07/11 18:36:24 session worker[5] started
2021/07/11 18:36:24 session worker[6] started
2021/07/11 18:36:24 session worker[7] started
2021/07/11 18:36:24 session worker[8] started
2021/07/11 18:36:24 session worker[9] started
2021/07/11 18:36:24 session worker[10] started
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50957->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50960->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50964->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50965->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50959->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50956->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50958->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50963->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50962->公网ip:23306: i/o timeout, retrying...
2021/07/11 18:36:26 connection err: read tcp 10.133.96.44:50961->公网ip:23306: i/o timeout, retrying...`
3. 桥接机日志
`2021/07/11 18:38:13 proxy on tunnel bridge mode [::]:13306
2021/07/11 18:38:15 server connection, key: default , id: 961c0e8b2da6c39bf7886ac946984d43b67728c8 tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: 9782df0a2ad40eb0d5dc94e832b5b8a1b390ada4 tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: 1721e766c86fd2794a4d4959aca4dcec5c8b5fab tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: 0fa3bfa72ca2d842607e3458c68dda5c8b47aa05 tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: 117adca219cb711768dbd2373aeebc6803c3f98d tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: 7efb114c6ce09dbc2fe3a1be2a96b9006ed3ba1d tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: d7547d5ccd22b7d28b16ab5606449ae371500693 tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: f0fc9ed7c84583fa2c0a5b98d1959882a4b33725 tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: 68c2dc3383d25eb2641e477d541fda7458310556 tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:15 server connection, key: default , id: bbba18a70d71b800175999b6bd7b423b8d53a8e1 tcp:10.0.250.59:3306 c43420cd26310ab4e547ec16e78c6fd31acc053d
2021/07/11 18:38:15 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists
2021/07/11 18:38:18 client default control conn not exists`

`2021/07/11 18:38:18 use tls parent 127.0.0.1:13306
2021/07/11 18:38:18 server id: 7894a4b8f56c2bbb2c404fe28e95a661391358c6
2021/07/11 18:38:18 proxy on tunnel server mode [::]:23306
2021/07/11 18:38:22 default conn b2ecb7bf162ad5549f4ff1adc8ec2625ad352bcb created
2021/07/11 18:38:22 default conn abbd5f4b50be3f424474976e46c87044dc8ee2b5 created
2021/07/11 18:38:22 default conn 941e2ba8355725a1f11b533f84018919e37a0ee9 created
2021/07/11 18:38:22 default conn 2b4dccd13a3993be8d548d75ff57b3da5d3b4d2a created
2021/07/11 18:38:22 default conn 6571450389f44a252cf22350122429cfe048fc2b created
2021/07/11 18:38:22 default conn 4153c80dd23b312732ea352458b87b145c4a95d5 created
2021/07/11 18:38:22 default conn 1b7bff9f9af40c49dc432413f07f0a0a2e47feb4 created
2021/07/11 18:38:22 default conn 0b7fe84d66f4170e430551348a5ad43a73cc20cd created
2021/07/11 18:38:22 default conn 6cd6b1a2434836d6458dbb44ec7a303c40f26fad created
2021/07/11 18:38:22 default conn 6862e4b9c338522f6c7128f831e9612630480951 created
2021/07/11 18:38:24 default conn 941e2ba8355725a1f11b533f84018919e37a0ee9 released
2021/07/11 18:38:24 default conn abbd5f4b50be3f424474976e46c87044dc8ee2b5 released
2021/07/11 18:38:24 default conn 1b7bff9f9af40c49dc432413f07f0a0a2e47feb4 released
2021/07/11 18:38:24 default conn 6862e4b9c338522f6c7128f831e9612630480951 released
2021/07/11 18:38:24 default conn 4153c80dd23b312732ea352458b87b145c4a95d5 released
2021/07/11 18:38:24 default conn 6cd6b1a2434836d6458dbb44ec7a303c40f26fad released
2021/07/11 18:38:24 default conn b2ecb7bf162ad5549f4ff1adc8ec2625ad352bcb released
2021/07/11 18:38:24 default conn 0b7fe84d66f4170e430551348a5ad43a73cc20cd released
2021/07/11 18:38:24 default conn 6571450389f44a252cf22350122429cfe048fc2b released
2021/07/11 18:38:24 default conn 2b4dccd13a3993be8d548d75ff57b3da5d3b4d2a released
`

请问是哪里出现问题了呢？
@snail007

**Comment by happygl16** [comment]
我也有相似的问题 ，就是一旦断网 重连机制会卡住不执行 这个怎么设置啊  让timeout变的非常大

**Comment by snail007** [comment]
首次使用必现 timeout 大概率是防火墙问题，另外命令help有全部参数， 包括超时。
