### ISSUE TITLE
请问我想利用proxy做拦截器，应该怎么做优雅，访问记录通过代理，我能通过chanel进行相关策略调整(重定向、阻断、保存资源等)

### ISSUE THREAD

**Issue by xx-zhang** [snail007/goproxy#441]
RT
## Steps to Reproduce

1.
1.
1.
1.

## Context (Environment)

1. proxy version is : v?
1. full command is :?
1. system is :
1. full log is: ?

**Comment by xx-zhang** [comment]
我之前用的  [mitmproxy](https://github.com/mitmproxy/mitmproxy)

**Comment by snail007** [comment]
商业版：流量上报，认证API结合使用可以实现。

**Comment by xx-zhang** [comment]
> 商业版：流量上报，认证API结合使用可以实现。

刚刚问了同事，已经5min手撸成功。
