### ISSUE TITLE
商业版问题 functions.go:178: bind crashed runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nginxzzz** [snail007/goproxy#448]
商业版sps，使用--auth-file并在返回结果中指定了upstream时报错functions.go:178: bind crashed runtime error: invalid memory address or nil pointer dereference， 不指定upstream没问题。 如何解决？  
版本已经更新至最新

**Comment by snail007** [comment]
请按着issue模版填写。
