### ISSUE TITLE
Block all domains by default

### ISSUE THREAD

**Issue by idanielblake** [snail007/goproxy#46]
Hello
I want to only whitelist specific domains on our web proxy.  I can't find a solution. Is that possible with goproxy?
I hope this is a right place to ask questions.
Thank you

**Comment by snail007** [comment]
Currently,block all domains by default proxy not supported ,but you can use auth api to control every connection as you wish,auth docs at  
http(s) : https://github.com/snail007/goproxy#15basic-authentication
socks5 : https://github.com/snail007/goproxy#57authentication
