### ISSUE TITLE
SPS mode not work with Android

### ISSUE THREAD

**Issue by Raymond-C** [snail007/goproxy#462]
Work in PCs but shows error "WARN connect to tcp parent  fail, ERR:cmd associate not supported" when try to connet in Android device

## Expected Behavior
Android device can work 

## Current Behavior
Try to connect with Shadowrocket_9.6 / BifristV_0.6.3 / v2RayNG_1.3.1 , all not work ,came with same error

## Context (Environment)
proxy version is : commercial_11.3

full command is : proxy sps -S socks -T tcp -p :12345 -a aa:bb:500:0: -P socks5://xxxx:xxx@a.b.c.d

system is : ubuntu 20.4

Below is  full log
2022/01/10 13:46:23.537152 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51755 from 8.218.14.68:51755
2022/01/10 13:46:23.946307 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51757 from 8.218.14.68:51757
2022/01/10 13:46:23.946606 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51759 from 8.218.14.68:51759
2022/01/10 13:46:23.948229 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51756 from 8.218.14.68:51756
2022/01/10 13:46:25.386507 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51771 from 8.218.14.68:51771
2022/01/10 13:46:25.794262 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51775 from 8.218.14.68:51775
2022/01/10 13:46:25.800645 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51774 from 8.218.14.68:51774
2022/01/10 13:46:25.995680 WARN connect to tcp parent  fail, ERR:cmd associate not supported, form: 8.218.14.68:51778 from 8.218.14.68:51778

**Comment by snail007** [comment]
sdk's sps is commercial edition feature

**Comment by Raymond-C** [comment]
Hi, I am testing with commercial Version

And I have further findings:
Even though I am visiting same destination, Android APP request in UDP protocol while Win/IOS program request in TCP protocol.

The proxy can run after dropping the parent node 
> `proxy sps -S socks --udp-port 0 --udp -T tcp -p :12345 -a aa:bb:500:0:`

If parent node is no authenticated one, below command can work perfect
> `proxy sps -S socks --udp-port 0 --udp -T tcp -p :12345 -a aa:bb:500:0: -P socks5://1.2.3.4:8080`

However, I am expecting  to use with authenticated parent like `socks5://a:b@1.2.3.4:8080`
> `proxy sps -S socks --udp-port 0 --udp -T tcp -p :12345 -a aa:bb:500:0: -P socks5://a:b@1.2.3.4:8080`
and get some new errors
```
2022/01/11 02:43:02.517423 WARN udp outgoing error: proxy: SOCKS5 proxy at 0.0.0.0:0 failed to connect: command not supported
2022/01/11 02:43:02.601543 WARN udp outgoing error: proxy: SOCKS5 proxy at 0.0.0.0:0 failed to connect: command not supported
```


Is there any way to resolve this issue?

**Comment by snail007** [comment]
pls supply the "Steps to Reproduce", in order to debug the issue fastly.

**Comment by Raymond-C** [comment]
Seems to be DNS issue
If I define a specified DNS address is Android setting,the issue will be solved
The PC software will set a random DNS by default while Android one not
