### ISSUE TITLE
I want goproxy service go whit sockt5 proxy

### ISSUE THREAD

**Issue by zhubinsheng** [snail007/goproxy#468]

**Comment by zhubinsheng** [comment]
how can i do ?

**Comment by zhubinsheng** [comment]
我用goproxy跑了一个http代理，但是上级配置的IP地址需要easyconnect提供的代理来支持；我用了https://github.com/Hagb/docker-easyconnect这个库 暴露了一个sockt5的代理端口，然后我想让goproxy走这个sockt5的代理端口

**Comment by snail007** [comment]
看手册，指定上级参数。

**Comment by zhubinsheng** [comment]
已经用命令行实现感谢作者
