### ISSUE TITLE
support socks5 username/password (rfc1929)

### ISSUE THREAD

**Issue by JonasGao** [snail007/goproxy#47]
can you supporting [rfc1929](https://www.ietf.org/rfc/rfc1929.txt).

**Comment by snail007** [comment]
proxy already supported it，you can find it via：https://github.com/snail007/goproxy#57authentication

**Comment by JonasGao** [comment]
oh, i mean, second level SOCKS need auth. 
i already have a SOCKS proxy, it need auth.
then, i want convert it to HTTP....

like `./proxy http -t tcp -p :33080 -T tcp -P "22.22.22.22:8080" -A "xxx:yyy"`
and, `"xxx:yyy" use to `"22.22.22.22:8080"`

**Comment by snail007** [comment]
i see,this feature will coming soon,please keep watching project.

**Comment by snail007** [comment]
done.
via: https://github.com/snail007/goproxy#66authentication
