### ISSUE TITLE
V11.6 版本 在443端口开启二级HTTP代理，DNS解析到代理服务器报错

### ISSUE THREAD

**Issue by pengzai-dev** [snail007/goproxy#472]
V11.6 版本 代理服务器在443端口开启二级HTTP代理，DNS解析到代理服务器有报错无法正常使用，
试了旧的版本是好的
1、这个bug后续会修复吗
2、可否至少保留两个版本，这样遇到问题后方便回退到上个版本

**Comment by flyzxt** [comment]
商业版本存在同样问题！！！历史版本至少保留1-2个版本吧。否则太影响使用了。

**Comment by snail007** [comment]
写一下复现步骤，才能确定是否有问题，问题所在。

**Comment by snail007** [comment]
下个版本已经修复
