### ISSUE TITLE
UDP代理30秒没有数据收发会released

### ISSUE THREAD

**Issue by Jierui** [snail007/goproxy#477]
cmd: ./proxy udp --timeout=10000 -p ":15353" -T udp -P "127.0.0.1:15061"
不过timeout参数设置为大于30s还是小于30s实际表示超时时间都是30s
2022/04/14 02:48:05.633531 INFO udp conn 192.168.20.13:5061 <--> :15353 connected
2022/04/14 02:48:36.760898 INFO udp conn 192.168.20.13:5061 <--> :15353 released

**Comment by Jierui** [comment]
这个是connect timeout参数，udp released参数怎么设置呢，我想时间更长些

**Comment by snail007** [comment]
udp无状态，没有超时一说。

**Comment by Jierui** [comment]
2022/04/14 02:48:36.760898 INFO udp conn 192.168.20.13:5061 <--> :15353 released，释放服务端发回来的命令客户端收不到了，如果是connected状态就没有问题， 30秒没数据经过代理就会自动释放这个peer吗，有没有办法可以控制久一点呢

**Comment by snail007** [comment]
这个时间目前写死的

**Comment by Jierui** [comment]
多谢你的解答，你看后续版本会不会考虑下把这个参数开放出来可配置，有些场景恰好过了30多秒回复，但是代理通道已经关闭了；

**Comment by snail007** [comment]
下个版本考虑加上参数控制这个gc时间。

**Comment by snail007** [comment]
done
