### ISSUE TITLE
能否在 SOCKS 代理中为 <IP 地址>:<端口号> 设置黑白名单

### ISSUE THREAD

**Issue by Menci** [snail007/goproxy#49]
情景：X 机器向外网开放一个端口，提供一个 SOCKS 代理，但客户端只能通过该代理连接到 127.0.0.1:443。

**Comment by Menci** [comment]
如果能设置不同的验证凭据，凭据 A 可以任意连接，凭据 B 受黑白名单限制，就更好了。

**Comment by snail007** [comment]
你可以参考认证api，开启验证，通过外部api控制每一个连接
