### ISSUE TITLE
-m -z参数好像没法用了

### ISSUE THREAD

**Issue by twomazikebei** [snail007/goproxy#495]
环境centos8
./proxy -v  输出 free_11.9

一级代理[192.168.1.100]运行 
./proxy socks -t tcp -z mypwd -m -p "0.0.0.0:8080"

二级代理[192.168.1.110]
./proxy sps -S http -T tcp -P "192.168.1.100:8080" -Z mypwd -M  -t tcp -p :8888

客户端[192.168.1.120]
curl --proxy "http://192.168.1.110:8888"  http://baidu.com
curl --sockes5 192.168.1.110:8888  http://baidu.com

一级代理提示
 WARN handshake fail, ERR: new methods request fail,ERR: read tcp xxx.xxx.xxx.xxx->xxx.xxx.xxx.xxx:yyy: i/o timeout

二级代理提示
 WARN handshake fail, proxy: failed to read greeting from SOCKS5 proxy at xxx.xxx.xxx.xxx: read tcp xxx.xxx.xxx.xxx:yyy->xxx.xxx.xxx.xxx:yyy: i/o timeout

 WARN connect to tcp parent 192.168.1.100:8080 fail, ERR:proxy: failed to read greeting from SOCKS5 proxy at 1 xxx.xxx.xxx.xxx:80: read tcp  xxx.xxx.xxx.xxx:yyy-> xxx.xxx.xxx.xxx:yyy: i/o timeout from  xxx.xxx.xxx.xxx:yyy

一级代理和二级代理同时单独使用-m 或-z也出现上述提示

只有一级和二级同时取消-m -z参数能正常使用

使用历史版本free_10
直接替换proxy文件，使用-m -z参数能正常使用，无任何警告提示

**Comment by snail007** [comment]
你上级是socks5，你在下级指定上级是 -S http类型，当然不通了。

**Comment by twomazikebei** [comment]
./proxy sps -S socks -T tcp -P "192.168.1.100:8080" -Z mypwd -M -t tcp -p :8888
是我测试 socks 时候以为是模式的问题，所以两端都换成了http, 导致贴上来 复制错了代码
因为我换到低版本，就替换一下proxy主程序，-m  -z参数就能正常使用

**Comment by snail007** [comment]
下个版本12.0已经修复。
