### ISSUE TITLE
黑名单域名文件在配置--auth-url不生效

### ISSUE THREAD

**Issue by mjh-jason** [snail007/goproxy#497]
## Expected Behavior

1.预期是根据黑名单文件内的内容进行拦截

## Possible Solution

1.配置了auth-url后，黑名单域名文件不生效

## Steps to Reproduce

![51J@`$XTLFEWOHN8 OSX9QG](https://user-images.githubusercontent.com/63330349/188251041-53e07b3b-fa29-4fc9-a952-09dc3929f838.png)

## Context (Environment)

1. proxy version is : 最新的商业版
1. full command is : proxy @configfile.txt
1. system is : centos7

## Detailed Description
1.黑名单域名文件不生效，不知道是不是我哪里配错的问题，望指教，谢谢

**Comment by snail007** [comment]
socks5代理协议下，客户端可以决定是否使用代理解析域名，如果客户端先把域名在客户端本地解析成IP，再让代理连接IP，你设置的黑名单里面却写的是域名，这时候根本不能匹配上，也就不能拦截。

**Comment by mjh-jason** [comment]
非常感谢作者的回复。
HTTP代理协议下也不支持是吗？我这边测试了发现HTTP也拦截不了。
有办法限制客户端使用代理IP解析域名吗？
如果域名套了CDN是不是没办法拦截？

**Comment by snail007** [comment]
是否解析域名后让代理连接ip，是客户端单方面行为，代理软件不能控制。
