### ISSUE TITLE
能否支持GRE协议 转发

### ISSUE THREAD

**Issue by jrt324** [snail007/goproxy#51]
能否支持GRE协议 转发？
场景是这样的，公司内网一台服务器作为pptp 的vpn服务器，有一个公网vps，希望在家里通过vps的ip连接公司的vpn服务器，目前尝试都是失败的，貌似原因应该是goproxy目前没有代理GRE协议支持，不知道我说的对不对

**Comment by snail007** [comment]
我查了一下，pptp使用的是tcp：1723端口，所以你需要用内网穿透，把公司的1723端口映射到vps上的1723端口即可。

**Comment by jrt324** [comment]
这个方法我试过了，还是不行，1732端口确定映射了，而且telnet 测试是可以的，但是实际客户端连接的时候还是出现连接不上的问题，所以我估计不光是开一个1732端口的问题

**Comment by snail007** [comment]
确实，我又查了一下。基于pptp的vpn防火墙该开哪些端口？答：IPSEC：500、PPTP：4500、1723、L2TP:1701
看来再映射一下500，4500，1701端口即可。

**Comment by snail007** [comment]
可以参考一下bbs.chinaunix.net/thread-1800326-1-1.html

**Comment by jrt324** [comment]
这几个端口都隐射过了，有几个应该是udp端口，验证是通过了，不过最终还是失败了，我估计应该是GRE协议的问题，你给的这个链接里面也提到GRE协议，貌似和端口无关

> pptp需要GRE协议的支持，跟端口号没有关系。

可以看/etc/protocols里面的内容。

**Comment by snail007** [comment]
如果这样，那么理论上就解决不了了，gp只能解决tcp层面的问题。

**Comment by 1265578519** [comment]
iptables gre开启转发不就行了。。pptp数据连接用的是gre，没有端口的，真要说是udp端口47
