### ISSUE TITLE
free_12.2  tserver crashed 

### ISSUE THREAD

**Issue by liyiwu** [snail007/goproxy#510]
free_12.2  tserver crashed 

## Context (Environment)

1. proxy version is : free_12.2
1. full command is : proxy tserver -r :22080@:80 -P 127.0.0.1:33080 -C proxy.crt -K proxy.key --forever --log=proxy.log
1. system is : Debian GNU/Linux 11 (bullseye)
1. full log is:
   ERROR err : run service [tserver:tserver] fail, ERR:tserver servcie crashed, ERR: interface conversion: interface {} is tunnel.TunnelServerArgs, not *tunnel.TunnelServerArgs
trace:goroutine 1 [running]:
runtime/debug.Stack(0xc0001242f0, 0xdc1e20, 0xc000241080)
        /usr/local/go1.16.3/src/runtime/debug/stack.go:24 +0x9f
github.com/snail007/proxy/services.Run.func1(0x7ffda2536eb6, 0x7, 0xc0001248a8)
        proxy/services/service.go:101 +0x76
panic(0xdc1e20, 0xc000241080)
        /usr/local/go1.16.3/src/runtime/panic.go:965 +0x1b9
github.com/snail007/proxy/services/tunnel.(*TunnelServer).Start(0xc00026e0d0, 0xe8ff60, 0xc000030a50, 0x1027a28, 0xc0002220a0, 0xc000220fb0, 0xd)
        proxy/services/tunnel/tunnel_server.go:315 +0x707
github.com/snail007/proxy/services/tunnel.(*TunnelServerManager).Start(0xc0001fe690, 0xd58480, 0xc0000309a0, 0x1027a28, 0xc0002220a0, 0x1, 0x0)
        proxy/services/tunnel/tunnel_server.go:153 +0x7f1
github.com/snail007/proxy/services.Run(0x7ffda2536eb6, 0x7, 0x0, 0x0, 0xc000240f90, 0x0, 0x0)
        proxy/services/service.go:108 +0x2bd
github.com/snail007/proxy/core/runner.doStart(0x7ffda2536eb6, 0x7, 0xc000064690, 0x6e, 0x0, 0x0, 0x1027a28, 0xc0002220a0, 0xf, 0xc00007c000, ...)
        proxy/core/runner/runner.go:988 +0x101b8
github.com/snail007/proxy/core/runner.StartWithLogger(...)
        proxy/core/runner/runner.go:74
main.main()
        proxy/main.go:84 +0x145

**Comment by snail007** [comment]
be fixed in next version
