### ISSUE TITLE
确定支持websocket?

### ISSUE THREAD

**Issue by xuiv01** [snail007/goproxy#52]
怎么用的？

**Comment by xuiv01** [comment]
我测试了，websocket 无法使用，现在的vps 都只能用 websocket

**Comment by snail007** [comment]
你怎么测试的？wb是可以用的。

**Comment by xuiv01** [comment]
用c9.io测试的，c9.io只能侦听8080端口，这端口只能走http,https,websokcet，对外c9会把8080映射成80，443，wstunnel,gost,websockify+shadowsocks,shadowsocks-over-websocks都能正常使用，但是goproxy工作不正常，client和server能联系到，但是都报错，可能被c9过滤了。我想在路由器上实现全局代理，但是没办法把websocket封装过的包转成tcp,udp的包，websockify只能把tcp包转成websocket，不能转回去，有两个tcp2ws的程序能转回去，但是golang和java写的，路由器没FPU，只能用c写的程序，golang指定GOARCH=mipsle GOMIPS=softfloat编译出来的gost卡成狗，经常无响应。我找shadows-libev的维护者把websocket支持加进去，他说没这个计划，头疼。

**Comment by xuiv01** [comment]
websockify的c代码在https://github.com/novnc/websockify/tree/master/other

你有空就帮我改一下。
