### ISSUE TITLE
--dns 参数不可使用

### ISSUE THREAD

**Issue by InoryS** [snail007/goproxy#529]
## Expected Behavior

支持 --dns 参数  `./proxy http --dns 8.8.8.8 -t tcp -p :80,:443 -T tcp --intelligent=parent --jumper socks5://foo:bar@example.com:42321`

## Current Behavior

文档中 [HTTP(S)反向代理](https://snail007.host900.com/goproxy/manual/zh/#/?id=_19-https%e5%8f%8d%e5%90%91%e4%bb%a3%e7%90%86) 建议 `proxy代理最好指定--dns 8.8.8.8参数`。实际上 --dns 不可以使用：

```
./proxy http --dns 8.8.8.8 -t tcp -p :80,:443 -T tcp --intelligent=parent --jumper socks5://foo:bar@example.com:42321
proxy/main.go:86 FATAL err : unknown long flag '--dns
```

## Steps to Reproduce

1.下载 goproxy
1. `./proxy http --dns 8.8.8.8 -t tcp -p :80,:443 -T tcp --intelligent=parent --jumper socks5://foo:bar@example.com:42321`
1.`proxy/main.go:86 FATAL err : unknown long flag '--dns`

## Context (Environment)

1. proxy version is : v13.0
1. full command is :  `./proxy http --dns 8.8.8.8 -t tcp -p :80,:443 -T tcp --intelligent=parent --jumper socks5://foo:bar@example.com:42321`
1. system is : Centos 7
1. full log is:  `proxy/main.go:86 FATAL err : unknown long flag '--dns`

**Comment by snail007** [comment]
`--dns-address` not `--dns`

**Comment by InoryS** [comment]
https://github.com/snail007/goproxy/commit/d3a2cf15c03dfe17f4ed2583c3714de951d4e6d5
