### ISSUE TITLE
FR: How to pring to logs without colorized ANSI escape sequences

### ISSUE THREAD

**Issue by HectorB-2020** [snail007/goproxy#557]
## Expected Behavior
There should be a command line parameter that that prevents printing colorized ANSI escape sequences to logs

## Current Behavior

Currently the program sends ANSI escape sequences to logs even if Windows terminal does not support this

## Possible Solution
A CLI parameter like `proxy.exe --logs-no-color`.

## Steps to Reproduce

1. Start the program, watch its output
```bat
proxy.exe http -t tcp -p "0.0.0.0:8088"
```

## Context (Environment)

1. proxy version is : free_14.1
1. full command is : proxy.exe http -t tcp -p "0.0.0.0:8088"
1. system is : Windows 10 x86_64

**Comment by snail007** [comment]
use the latest version, colour text is disabled in windows.

**Comment by HectorB-2020** [comment]
Indeed! Thanks very much!
