### ISSUE TITLE
UDP proxy does not work properly

### ISSUE THREAD

**Issue by PtDragon** [snail007/goproxy#57]
I did  a try to use it in UDP proxy mode for my KCP on other server and it did not work.
Does UDP proxy forward all UDP packets properly?

**Comment by snail007** [comment]
what the starting command is? And the log?

**Comment by PtDragon** [comment]
proxy udp --local="local_ip:22001" -T udp -L 0 -I 0 -P "remote_ip:22001" --forever --daemon

**Comment by PtDragon** [comment]
log
2018/04/20 02:26:49 worker proxy [PID] 1266 running...

                ########  ########   #######  ##     ## ##    ##
                ##     ## ##     ## ##     ##  ##   ##   ##  ##
                ##     ## ##     ## ##     ##   ## ##     ####
                ########  ########  ##     ##    ###       ##
                ##        ##   ##   ##     ##   ## ##      ##
                ##        ##    ##  ##     ##  ##   ##     ##
                ##        ##     ##  #######  ##     ##    ##

                v4.6 by snail , blog : http://www.host900.com/

2018/04/20 02:26:49 use udp parent remote_ip:22001
2018/04/20 02:26:49 udp proxy on local_ip:22001
