### ISSUE TITLE
verify fail, your machine has expired（free_14.8）

### ISSUE THREAD

**Issue by MrXionGe** [snail007/goproxy#576]
# 为避免浪费时间，一切不按着issue模版填写的问题，一律默认忽略处理，谢谢合作！
# Avoid waste time, any report not match the issue template will be ignored.

## Expected Behavior

cmd
``` shell
./proxy http -t tcp -p ":8880"
```
Then listening...
## Current Behavior

cmd show
``` shell
2024/12/23 16:05:10.536 INFO tcp http(s) proxy on [::]:8880
2024/12/23 16:05:15.533 INFO your machine code is : 9a76cd59a5e9469bc682bfd093b49927
2024/12/23 16:05:15.533 INFO checking ...
2024/12/23 16:05:55.773 INFO verify fail, your machine has expired
```
## Steps to Reproduce

1. Download latest version（v14.8）
1. Decompress the file (proxy-linux-amd64.tar.gz)
1. Run proxy
1. Console print "verify fail, your machine has expired"

## Context (Environment)

1. proxy version is: free_14.8
1. full command is: ./proxy http -t tcp -p ":8880"
1. system is: Ubuntu 22.04.5 LTS
1. full log is: 
```
2024/12/23 16:05:10.536 INFO tcp http(s) proxy on [::]:8880
2024/12/23 16:05:15.533 INFO your machine code is : 9a76cd59a5e9469bc682bfd093b49927
2024/12/23 16:05:15.533 INFO checking ...
2024/12/23 16:05:55.773 INFO verify fail, your machine has expired
```

**Comment by snail007** [comment]
fixed, try redownload

**Comment by MrXionGe** [comment]
It has been verified. Confirm that the error has been fixed.
