### ISSUE TITLE
多vps情况，如何随意选择使用哪个？

### ISSUE THREAD

**Issue by rainsun007** [snail007/goproxy#73]
@snail007   请教个问题

场景：
有5个vps， 想同时代理同一台机器的电脑(比如自己的笔记本)，需要随意指定使用哪个代理，5个代理必须同时启动

看了个文档 ， 没找到说明， 不知这个场景是否支持，应如何操作

**Comment by snail007** [comment]
这种情况可以配合haproxy的tcp代理你的五个vps，haproxy暴露一个端口给你的笔记本。

**Comment by rainsun007** [comment]
用haproxy是做了高可用    想随意调用代理的问题还在      想了一下   是否可以启动5个代理  设置5个不同的本地端口号    然后在选择使用代理时通过使用不同的端口号来操作

**Comment by rainsun007** [comment]
多谢   我搞下试试   搞不定再来请教

**Comment by rainsun007** [comment]
@snail007    代理的问题可以解决   为了安全隐藏真实ip  需要高匿代理   这个现在支持吗

**Comment by snail007** [comment]
纯转发,本来就是高匿名

**Comment by wwu** [comment]
请问haproxy的心跳检查应该如何设置? 我尝试直接tcp ping vps代理端口(比如38080), 但是心跳包报错.

**Comment by snail007** [comment]
tcp和ping是两个协议

**Comment by wwu** [comment]
不知道proxy这边有没有暴露一个类似echo或者ping的端口, 这样可以给haproxy心跳检查用.

**Comment by snail007** [comment]
ping是ICMP协议 不是TCP

**Comment by snail007** [comment]
v6.0多个上级支持负载均衡高可用。

**Comment by wwu** [comment]
多谢 ，问题已解决。
