### ISSUE TITLE
支持公司的代理吗?

### ISSUE THREAD

**Issue by haydonchou** [snail007/goproxy#78]
公司上网需要加代理a才能访问互联网，公司把我的需要访问的资源屏蔽了，在公司通过代理a可以访问外网vps，vps可以访问我的资源，相当于我想搭建一个自己的正向代理服务器通过vps访问互联网，但是在访问vps时需要加上公司代理a，看文档好像没有啊。

**Comment by snail007** [comment]
你意思上proxy通过中间代理a连接上级vps上面的proxy，现在还不能这样。

**Comment by cn4** [comment]
@haydonchou https://github.com/nadoo/glider

**Comment by snail007** [comment]
added in v5.4

**Comment by haydonchou** [comment]
@snail007 我的意思是走正向代理访问互联网的proxy，本地启动一个端口。因为公司屏蔽了走正向代理的某些软件，但是正向代理跟互联网的proxy没有屏蔽。不知道这个是怎么设置的。公司的所有内部机器都不能直接访问互联网，都需要通过正向代理访问。现在是使用的proxychains4+polipo实现的。

**Comment by haydonchou** [comment]
@snail007 之前还用过一个东西，叫desproxy。但是这东西多次握手，而且是占用线程的，默认只有10个线程，我改成1000，但是多人使用还是没有proxychains4+polipo稳定。

**Comment by snail007** [comment]
v5.4 tcp端口映射功能，可以透过公司代理把vps端口映射到本地，程序连接本地映射端口就是连接vps的端口.
