### ISSUE TITLE
Windows版运行一天proxy.exe占用大约2g内存

### ISSUE THREAD

**Issue by cuiweieee** [snail007/goproxy#80]
开了一个http代理和一个sock5代理
http -t tcp -p :3128 --log ..\logs\http.log --daemon --forever
socks -t tcp -p :1080 --log ..\logs\sock5.log --daemon --forever

sock5代理的内存一直在涨

**Comment by cuiweieee** [comment]
开了一个http代理和一个sock5代理
http -t tcp -p :3128 --log ..\logs\http.log --daemon --forever
socks -t tcp -p 3128 --log ..\logs\sock5.log --daemon --forever

sock5代理的内存一直在涨

**Comment by cuiweieee** [comment]
版本是4.7

**Comment by snail007** [comment]
socks -t tcp -p 3128 这个命令格式不对吧.端口全面要有:

**Comment by cuiweieee** [comment]
有的有的，之前打错了

**Comment by snail007** [comment]
什么版本的Windows，是不是win10？

**Comment by cuiweieee** [comment]
不是win10，是windows server 2008 r2，今天用了goproxy-jui大约4个小时jvm内存溢出了，javaw进程自动关闭了

**Comment by snail007** [comment]
只有socks？

**Comment by cuiweieee** [comment]
两个，一个http一个socks，命令行用两个proxy.exe启动，jui版本的添加了两个服务，这样

**Comment by snail007** [comment]
只有socks占内存？

**Comment by cuiweieee** [comment]
是的，socks5有20多人在用

**Comment by snail007** [comment]
看你启动命令http和socks监听都用的相同tcp端口，一个机器上不能这样吧

**Comment by cuiweieee** [comment]
不好意思啊，也是写错了，不是同一端口

**Comment by snail007** [comment]
问题已经定位,进Q群,我给你一个调试版本,你测试看看.

**Comment by cuiweieee** [comment]
好的
