### ISSUE TITLE
发现有异常的dns请求

### ISSUE THREAD

**Issue by soopsio** [snail007/goproxy#81]
程序会发起不必要的DNS 请求，有时候会有请求被代理到 阿里云的服务器，出现404 或者 403 ，这是什么原因？
有很多dns请求查询的是 不存在的域名，像是随机的，但是没有后缀

**Comment by snail007** [comment]
不是proxy主动程序发起的,是客户端发起的代理请求，proxy不会自己发起任何请求.

**Comment by soopsio** [comment]
我把本地的proxy 进程停掉之后就再没有发起的dns请求了

**Comment by snail007** [comment]
有个智能检测,只要访问过一次那个域名就会进入检查列表,定期检查，触发者还是客户端。
