### ISSUE TITLE
外部API认证支持仅认证IP和target

### ISSUE THREAD

**Issue by LunacyZeus** [snail007/goproxy#92]
先说下问题:
这边我这里是使用程序为公司的爬虫代理池提供服务,貌似当前的外部认证API是需要提供Proxy-Authorization字段才能继续访问.........我这里客户端有的不支持设置这个字段
我看了structs.go这个文件的第460行,发现如果用户名和密码不存在就不会通过api请求验证
我这里通过修改structs.go文件让代理可以仅验证IP和target

希望作者大大能考虑在下一个版本支持这个功能~~~
感谢辛苦付出!!!

**Comment by snail007** [comment]
你的需求比较定制化，建议维护自己的分支

**Comment by LunacyZeus** [comment]
okay 感谢回复
