### ISSUE TITLE
太强大了 有没有小白级别的入门教程啊 

### ISSUE THREAD

**Issue by ishangxue** [snail007/goproxy#93]
想要实现的目标：
我在公式内网一台电脑架设了一个web服务器，因为没有路由权限，所以需要实现内网穿透，让外网可以访问我在公司内网的服务器。
曾用过花生壳等内网穿透，但是太垃圾了。经常连不上。
请问这个能实现内网穿透吧：：：
各位大侠给个步骤呗，一头雾水整不明白啊 。系统是window7

**Comment by snail007** [comment]
[](https://github.com/snail007/goproxy/wiki/%E4%BD%BF%E7%94%A8goproxy%E5%AE%9E%E7%8E%B0%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F)
