### ISSUE TITLE
goproxy不能使用xx-net作为一级代理

### ISSUE THREAD

**Issue by sparo-jack** [snail007/goproxy#95]
goproxy是不是不能通过部署appid来代理请求？
goproxy使用xx-net作为一级代理，发送请求后出现socket error or timeout？是怎么回事？

**Comment by snail007** [comment]
没明白你怎么用的,appid又是什么,架构是怎么样的.

**Comment by sparo-jack** [comment]
xx-net你知道吗？就是我翻墙都是使用的xx-net, xx-net之所以能翻墙是因为部署了的google的appid。
我的xx-net监听8087端口
因为proxy.exe http -t tcp -p "0.0.0.0:8090"不能直接翻墙。
所以使用proxy.exe http -t tcp -p "0.0.0.0:8090" -T tcp -P "127.0.0.1:8087"，使用0.0.0.0:8090作为二级代理，xx-net作为一级代理。希望8090端口接收到其它机器请求时，把需要翻墙的请求转发给8087端口，由xx-net进行翻墙。但现在另外一台机器连到8090端口后出现socket error or timeout

**Comment by snail007** [comment]
你的问题如下:
1.tcp模式等于裸奔,会被监控,你不可能成功.
2.协议不对,你goproxy启动的是http代理,连接的上级也必须是http代理,但是现在看到的错误信息你的xxnet是socks代理,肯定不能通信.
3.goproxy不支持google的appid.
4.要科学上网,请看[开心上网](https://github.com/snail007/goproxy/wiki/%E5%B0%8F%E7%99%BD%E5%BC%80%E5%BF%83%E4%B8%8A%E7%BD%91)

**Comment by snail007** [comment]
xxnet无论是否支持,二级和它走标准的tcp通讯,不加密肯定是行不通的,你不知道G*F*W的干嘛呢么..要科学上网,请看[开心上网](https://github.com/snail007/goproxy/wiki/%E5%B0%8F%E7%99%BD%E5%BC%80%E5%BF%83%E4%B8%8A%E7%BD%91)

**Comment by snail007** [comment]
仔细看了一下,"另外一台机器连到8090端口后出现socket error or timeout",说明你另外一个机器到这个地址不通,telnet看看.底层网络问题不是goproxy问题.

**Comment by sparo-jack** [comment]
因为请求是先到8090（goproxy），然后再到8087(xx-net)，如果是不需要正常翻墙的地址是可以正常访问的，但需要翻墙的地址就会出现“socket error or timeout”

**Comment by snail007** [comment]
socket error or timeout 是谁报的错,你现在的架构还不是很清晰,请弄个简单的完整的架构图

**Comment by birdofprey** [comment]
goproxy是一种很好的7层BGP路由器协议设计实现。对于企业级应用安全会有非常大的好处！！！感谢作者的付出

**Comment by sparo-jack** [comment]
socket error or timeout是goproxy显示出来的，但最终是xx-net导致的。后来在xx-net作者的帮助下，发现是xx-net只能处理请求页面端口是443的请求

**Comment by snail007** [comment]
那就是xxnet的协议实现不完整咯,proxy实现的是完整的http代理协议没有这些限制.

**Comment by sparo-jack** [comment]
是的，实现是不完整的
