### ISSUE TITLE
4.8版本开始的“反向代理模式” 80 端口反馈400 BAD REQUEST错误

### ISSUE THREAD

**Issue by uluca** [snail007/goproxy#97]
4.7版本无此问题，4.8和4.9报错

.\proxy http -t tcp -p :443,:80

访问HTTPS网站即443端口正常， HTTP网站反馈400错误

**Comment by snail007** [comment]
使用最新版,提供详细日志，网络环境。

**Comment by snail007** [comment]
fixed in v5.1
